/* AUTOGENERATED FILE. DO NOT EDIT. */
#include <string.h>
#include <stdlib.h>
#include <setjmp.h>
#include "cmock.h"
#include "Mockperiodic_callbacks.h"

static const char* CMockString_callback_count = "callback_count";
static const char* CMockString_periodic_callbacks__1000Hz = "periodic_callbacks__1000Hz";
static const char* CMockString_periodic_callbacks__100Hz = "periodic_callbacks__100Hz";
static const char* CMockString_periodic_callbacks__10Hz = "periodic_callbacks__10Hz";
static const char* CMockString_periodic_callbacks__1Hz = "periodic_callbacks__1Hz";
static const char* CMockString_periodic_callbacks__initialize = "periodic_callbacks__initialize";

typedef struct _CMOCK_periodic_callbacks__initialize_CALL_INSTANCE
{
  UNITY_LINE_TYPE LineNumber;
  int ExpectAnyArgsBool;
  CEXCEPTION_T ExceptionToThrow;

} CMOCK_periodic_callbacks__initialize_CALL_INSTANCE;

typedef struct _CMOCK_periodic_callbacks__1Hz_CALL_INSTANCE
{
  UNITY_LINE_TYPE LineNumber;
  int ExpectAnyArgsBool;
  uint32_t Expected_callback_count;
  CEXCEPTION_T ExceptionToThrow;
  int IgnoreArg_callback_count;

} CMOCK_periodic_callbacks__1Hz_CALL_INSTANCE;

typedef struct _CMOCK_periodic_callbacks__10Hz_CALL_INSTANCE
{
  UNITY_LINE_TYPE LineNumber;
  int ExpectAnyArgsBool;
  uint32_t Expected_callback_count;
  CEXCEPTION_T ExceptionToThrow;
  int IgnoreArg_callback_count;

} CMOCK_periodic_callbacks__10Hz_CALL_INSTANCE;

typedef struct _CMOCK_periodic_callbacks__100Hz_CALL_INSTANCE
{
  UNITY_LINE_TYPE LineNumber;
  int ExpectAnyArgsBool;
  uint32_t Expected_callback_count;
  CEXCEPTION_T ExceptionToThrow;
  int IgnoreArg_callback_count;

} CMOCK_periodic_callbacks__100Hz_CALL_INSTANCE;

typedef struct _CMOCK_periodic_callbacks__1000Hz_CALL_INSTANCE
{
  UNITY_LINE_TYPE LineNumber;
  int ExpectAnyArgsBool;
  uint32_t Expected_callback_count;
  CEXCEPTION_T ExceptionToThrow;
  int IgnoreArg_callback_count;

} CMOCK_periodic_callbacks__1000Hz_CALL_INSTANCE;

static struct Mockperiodic_callbacksInstance
{
  int periodic_callbacks__initialize_IgnoreBool;
  int periodic_callbacks__initialize_CallbackBool;
  CMOCK_periodic_callbacks__initialize_CALLBACK periodic_callbacks__initialize_CallbackFunctionPointer;
  int periodic_callbacks__initialize_CallbackCalls;
  CMOCK_MEM_INDEX_TYPE periodic_callbacks__initialize_CallInstance;
  int periodic_callbacks__1Hz_IgnoreBool;
  int periodic_callbacks__1Hz_CallbackBool;
  CMOCK_periodic_callbacks__1Hz_CALLBACK periodic_callbacks__1Hz_CallbackFunctionPointer;
  int periodic_callbacks__1Hz_CallbackCalls;
  CMOCK_MEM_INDEX_TYPE periodic_callbacks__1Hz_CallInstance;
  int periodic_callbacks__10Hz_IgnoreBool;
  int periodic_callbacks__10Hz_CallbackBool;
  CMOCK_periodic_callbacks__10Hz_CALLBACK periodic_callbacks__10Hz_CallbackFunctionPointer;
  int periodic_callbacks__10Hz_CallbackCalls;
  CMOCK_MEM_INDEX_TYPE periodic_callbacks__10Hz_CallInstance;
  int periodic_callbacks__100Hz_IgnoreBool;
  int periodic_callbacks__100Hz_CallbackBool;
  CMOCK_periodic_callbacks__100Hz_CALLBACK periodic_callbacks__100Hz_CallbackFunctionPointer;
  int periodic_callbacks__100Hz_CallbackCalls;
  CMOCK_MEM_INDEX_TYPE periodic_callbacks__100Hz_CallInstance;
  int periodic_callbacks__1000Hz_IgnoreBool;
  int periodic_callbacks__1000Hz_CallbackBool;
  CMOCK_periodic_callbacks__1000Hz_CALLBACK periodic_callbacks__1000Hz_CallbackFunctionPointer;
  int periodic_callbacks__1000Hz_CallbackCalls;
  CMOCK_MEM_INDEX_TYPE periodic_callbacks__1000Hz_CallInstance;
} Mock;

extern jmp_buf AbortFrame;

void Mockperiodic_callbacks_Verify(void)
{
  UNITY_LINE_TYPE cmock_line = TEST_LINE_NUM;
  CMOCK_MEM_INDEX_TYPE call_instance;
  call_instance = Mock.periodic_callbacks__initialize_CallInstance;
  if (Mock.periodic_callbacks__initialize_IgnoreBool)
    call_instance = CMOCK_GUTS_NONE;
  UNITY_SET_DETAIL(CMockString_periodic_callbacks__initialize);
  UNITY_TEST_ASSERT(CMOCK_GUTS_NONE == call_instance, cmock_line, CMockStringCalledLess);
  UNITY_CLR_DETAILS();
  if (Mock.periodic_callbacks__initialize_CallbackFunctionPointer != NULL)
    call_instance = CMOCK_GUTS_NONE;
  call_instance = Mock.periodic_callbacks__1Hz_CallInstance;
  if (Mock.periodic_callbacks__1Hz_IgnoreBool)
    call_instance = CMOCK_GUTS_NONE;
  UNITY_SET_DETAIL(CMockString_periodic_callbacks__1Hz);
  UNITY_TEST_ASSERT(CMOCK_GUTS_NONE == call_instance, cmock_line, CMockStringCalledLess);
  UNITY_CLR_DETAILS();
  if (Mock.periodic_callbacks__1Hz_CallbackFunctionPointer != NULL)
    call_instance = CMOCK_GUTS_NONE;
  call_instance = Mock.periodic_callbacks__10Hz_CallInstance;
  if (Mock.periodic_callbacks__10Hz_IgnoreBool)
    call_instance = CMOCK_GUTS_NONE;
  UNITY_SET_DETAIL(CMockString_periodic_callbacks__10Hz);
  UNITY_TEST_ASSERT(CMOCK_GUTS_NONE == call_instance, cmock_line, CMockStringCalledLess);
  UNITY_CLR_DETAILS();
  if (Mock.periodic_callbacks__10Hz_CallbackFunctionPointer != NULL)
    call_instance = CMOCK_GUTS_NONE;
  call_instance = Mock.periodic_callbacks__100Hz_CallInstance;
  if (Mock.periodic_callbacks__100Hz_IgnoreBool)
    call_instance = CMOCK_GUTS_NONE;
  UNITY_SET_DETAIL(CMockString_periodic_callbacks__100Hz);
  UNITY_TEST_ASSERT(CMOCK_GUTS_NONE == call_instance, cmock_line, CMockStringCalledLess);
  UNITY_CLR_DETAILS();
  if (Mock.periodic_callbacks__100Hz_CallbackFunctionPointer != NULL)
    call_instance = CMOCK_GUTS_NONE;
  call_instance = Mock.periodic_callbacks__1000Hz_CallInstance;
  if (Mock.periodic_callbacks__1000Hz_IgnoreBool)
    call_instance = CMOCK_GUTS_NONE;
  UNITY_SET_DETAIL(CMockString_periodic_callbacks__1000Hz);
  UNITY_TEST_ASSERT(CMOCK_GUTS_NONE == call_instance, cmock_line, CMockStringCalledLess);
  UNITY_CLR_DETAILS();
  if (Mock.periodic_callbacks__1000Hz_CallbackFunctionPointer != NULL)
    call_instance = CMOCK_GUTS_NONE;
}

void Mockperiodic_callbacks_Init(void)
{
  Mockperiodic_callbacks_Destroy();
}

void Mockperiodic_callbacks_Destroy(void)
{
  CMock_Guts_MemFreeAll();
  memset(&Mock, 0, sizeof(Mock));
}

void periodic_callbacks__initialize(void)
{
  UNITY_LINE_TYPE cmock_line = TEST_LINE_NUM;
  CMOCK_periodic_callbacks__initialize_CALL_INSTANCE* cmock_call_instance;
  UNITY_SET_DETAIL(CMockString_periodic_callbacks__initialize);
  cmock_call_instance = (CMOCK_periodic_callbacks__initialize_CALL_INSTANCE*)CMock_Guts_GetAddressFor(Mock.periodic_callbacks__initialize_CallInstance);
  Mock.periodic_callbacks__initialize_CallInstance = CMock_Guts_MemNext(Mock.periodic_callbacks__initialize_CallInstance);
  if (Mock.periodic_callbacks__initialize_IgnoreBool)
  {
    UNITY_CLR_DETAILS();
    return;
  }
  if (!Mock.periodic_callbacks__initialize_CallbackBool &&
      Mock.periodic_callbacks__initialize_CallbackFunctionPointer != NULL)
  {
    Mock.periodic_callbacks__initialize_CallbackFunctionPointer(Mock.periodic_callbacks__initialize_CallbackCalls++);
    UNITY_CLR_DETAILS();
    return;
  }
  UNITY_TEST_ASSERT_NOT_NULL(cmock_call_instance, cmock_line, CMockStringCalledMore);
  cmock_line = cmock_call_instance->LineNumber;
  if (Mock.periodic_callbacks__initialize_CallbackFunctionPointer != NULL)
  {
    Mock.periodic_callbacks__initialize_CallbackFunctionPointer(Mock.periodic_callbacks__initialize_CallbackCalls++);
  }
  if (cmock_call_instance->ExceptionToThrow != CEXCEPTION_NONE)
  {
    UNITY_CLR_DETAILS();
    Throw(cmock_call_instance->ExceptionToThrow);
  }
  UNITY_CLR_DETAILS();
}

void periodic_callbacks__initialize_CMockIgnore(void)
{
  Mock.periodic_callbacks__initialize_IgnoreBool = (int)1;
}

void periodic_callbacks__initialize_CMockExpect(UNITY_LINE_TYPE cmock_line)
{
  CMOCK_MEM_INDEX_TYPE cmock_guts_index = CMock_Guts_MemNew(sizeof(CMOCK_periodic_callbacks__initialize_CALL_INSTANCE));
  CMOCK_periodic_callbacks__initialize_CALL_INSTANCE* cmock_call_instance = (CMOCK_periodic_callbacks__initialize_CALL_INSTANCE*)CMock_Guts_GetAddressFor(cmock_guts_index);
  UNITY_TEST_ASSERT_NOT_NULL(cmock_call_instance, cmock_line, CMockStringOutOfMemory);
  memset(cmock_call_instance, 0, sizeof(*cmock_call_instance));
  Mock.periodic_callbacks__initialize_CallInstance = CMock_Guts_MemChain(Mock.periodic_callbacks__initialize_CallInstance, cmock_guts_index);
  Mock.periodic_callbacks__initialize_IgnoreBool = (int)0;
  cmock_call_instance->LineNumber = cmock_line;
  cmock_call_instance->ExceptionToThrow = CEXCEPTION_NONE;
  cmock_call_instance->ExpectAnyArgsBool = (int)0;
}

void periodic_callbacks__initialize_AddCallback(CMOCK_periodic_callbacks__initialize_CALLBACK Callback)
{
  Mock.periodic_callbacks__initialize_IgnoreBool = (int)0;
  Mock.periodic_callbacks__initialize_CallbackBool = (int)1;
  Mock.periodic_callbacks__initialize_CallbackFunctionPointer = Callback;
}

void periodic_callbacks__initialize_Stub(CMOCK_periodic_callbacks__initialize_CALLBACK Callback)
{
  Mock.periodic_callbacks__initialize_IgnoreBool = (int)0;
  Mock.periodic_callbacks__initialize_CallbackBool = (int)0;
  Mock.periodic_callbacks__initialize_CallbackFunctionPointer = Callback;
}

void periodic_callbacks__initialize_CMockExpectAndThrow(UNITY_LINE_TYPE cmock_line, CEXCEPTION_T cmock_to_throw)
{
  CMOCK_MEM_INDEX_TYPE cmock_guts_index = CMock_Guts_MemNew(sizeof(CMOCK_periodic_callbacks__initialize_CALL_INSTANCE));
  CMOCK_periodic_callbacks__initialize_CALL_INSTANCE* cmock_call_instance = (CMOCK_periodic_callbacks__initialize_CALL_INSTANCE*)CMock_Guts_GetAddressFor(cmock_guts_index);
  UNITY_TEST_ASSERT_NOT_NULL(cmock_call_instance, cmock_line, CMockStringOutOfMemory);
  memset(cmock_call_instance, 0, sizeof(*cmock_call_instance));
  Mock.periodic_callbacks__initialize_CallInstance = CMock_Guts_MemChain(Mock.periodic_callbacks__initialize_CallInstance, cmock_guts_index);
  Mock.periodic_callbacks__initialize_IgnoreBool = (int)0;
  cmock_call_instance->LineNumber = cmock_line;
  cmock_call_instance->ExceptionToThrow = CEXCEPTION_NONE;
  cmock_call_instance->ExpectAnyArgsBool = (int)0;
  cmock_call_instance->ExceptionToThrow = cmock_to_throw;
}

void periodic_callbacks__1Hz(uint32_t callback_count)
{
  UNITY_LINE_TYPE cmock_line = TEST_LINE_NUM;
  CMOCK_periodic_callbacks__1Hz_CALL_INSTANCE* cmock_call_instance;
  UNITY_SET_DETAIL(CMockString_periodic_callbacks__1Hz);
  cmock_call_instance = (CMOCK_periodic_callbacks__1Hz_CALL_INSTANCE*)CMock_Guts_GetAddressFor(Mock.periodic_callbacks__1Hz_CallInstance);
  Mock.periodic_callbacks__1Hz_CallInstance = CMock_Guts_MemNext(Mock.periodic_callbacks__1Hz_CallInstance);
  if (Mock.periodic_callbacks__1Hz_IgnoreBool)
  {
    UNITY_CLR_DETAILS();
    return;
  }
  if (!Mock.periodic_callbacks__1Hz_CallbackBool &&
      Mock.periodic_callbacks__1Hz_CallbackFunctionPointer != NULL)
  {
    Mock.periodic_callbacks__1Hz_CallbackFunctionPointer(callback_count, Mock.periodic_callbacks__1Hz_CallbackCalls++);
    UNITY_CLR_DETAILS();
    return;
  }
  UNITY_TEST_ASSERT_NOT_NULL(cmock_call_instance, cmock_line, CMockStringCalledMore);
  cmock_line = cmock_call_instance->LineNumber;
  if (!cmock_call_instance->ExpectAnyArgsBool)
  {
  if (!cmock_call_instance->IgnoreArg_callback_count)
  {
    UNITY_SET_DETAILS(CMockString_periodic_callbacks__1Hz,CMockString_callback_count);
    if (cmock_call_instance->Expected_callback_count != callback_count) {
    UNITY_TEST_ASSERT_EQUAL_HEX32(cmock_call_instance->Expected_callback_count, callback_count, cmock_line, CMockStringMismatch);
      }
  }
  }
  if (Mock.periodic_callbacks__1Hz_CallbackFunctionPointer != NULL)
  {
    Mock.periodic_callbacks__1Hz_CallbackFunctionPointer(callback_count, Mock.periodic_callbacks__1Hz_CallbackCalls++);
  }
  if (cmock_call_instance->ExceptionToThrow != CEXCEPTION_NONE)
  {
    UNITY_CLR_DETAILS();
    Throw(cmock_call_instance->ExceptionToThrow);
  }
  UNITY_CLR_DETAILS();
}

void CMockExpectParameters_periodic_callbacks__1Hz(CMOCK_periodic_callbacks__1Hz_CALL_INSTANCE* cmock_call_instance, uint32_t callback_count);
void CMockExpectParameters_periodic_callbacks__1Hz(CMOCK_periodic_callbacks__1Hz_CALL_INSTANCE* cmock_call_instance, uint32_t callback_count)
{
  cmock_call_instance->Expected_callback_count = callback_count;
  cmock_call_instance->IgnoreArg_callback_count = 0;
}

void periodic_callbacks__1Hz_CMockIgnore(void)
{
  Mock.periodic_callbacks__1Hz_IgnoreBool = (int)1;
}

void periodic_callbacks__1Hz_CMockExpectAnyArgs(UNITY_LINE_TYPE cmock_line)
{
  CMOCK_MEM_INDEX_TYPE cmock_guts_index = CMock_Guts_MemNew(sizeof(CMOCK_periodic_callbacks__1Hz_CALL_INSTANCE));
  CMOCK_periodic_callbacks__1Hz_CALL_INSTANCE* cmock_call_instance = (CMOCK_periodic_callbacks__1Hz_CALL_INSTANCE*)CMock_Guts_GetAddressFor(cmock_guts_index);
  UNITY_TEST_ASSERT_NOT_NULL(cmock_call_instance, cmock_line, CMockStringOutOfMemory);
  memset(cmock_call_instance, 0, sizeof(*cmock_call_instance));
  Mock.periodic_callbacks__1Hz_CallInstance = CMock_Guts_MemChain(Mock.periodic_callbacks__1Hz_CallInstance, cmock_guts_index);
  Mock.periodic_callbacks__1Hz_IgnoreBool = (int)0;
  cmock_call_instance->LineNumber = cmock_line;
  cmock_call_instance->ExceptionToThrow = CEXCEPTION_NONE;
  cmock_call_instance->ExpectAnyArgsBool = (int)0;
  cmock_call_instance->ExpectAnyArgsBool = (int)1;
}

void periodic_callbacks__1Hz_CMockExpect(UNITY_LINE_TYPE cmock_line, uint32_t callback_count)
{
  CMOCK_MEM_INDEX_TYPE cmock_guts_index = CMock_Guts_MemNew(sizeof(CMOCK_periodic_callbacks__1Hz_CALL_INSTANCE));
  CMOCK_periodic_callbacks__1Hz_CALL_INSTANCE* cmock_call_instance = (CMOCK_periodic_callbacks__1Hz_CALL_INSTANCE*)CMock_Guts_GetAddressFor(cmock_guts_index);
  UNITY_TEST_ASSERT_NOT_NULL(cmock_call_instance, cmock_line, CMockStringOutOfMemory);
  memset(cmock_call_instance, 0, sizeof(*cmock_call_instance));
  Mock.periodic_callbacks__1Hz_CallInstance = CMock_Guts_MemChain(Mock.periodic_callbacks__1Hz_CallInstance, cmock_guts_index);
  Mock.periodic_callbacks__1Hz_IgnoreBool = (int)0;
  cmock_call_instance->LineNumber = cmock_line;
  cmock_call_instance->ExceptionToThrow = CEXCEPTION_NONE;
  cmock_call_instance->ExpectAnyArgsBool = (int)0;
  CMockExpectParameters_periodic_callbacks__1Hz(cmock_call_instance, callback_count);
}

void periodic_callbacks__1Hz_AddCallback(CMOCK_periodic_callbacks__1Hz_CALLBACK Callback)
{
  Mock.periodic_callbacks__1Hz_IgnoreBool = (int)0;
  Mock.periodic_callbacks__1Hz_CallbackBool = (int)1;
  Mock.periodic_callbacks__1Hz_CallbackFunctionPointer = Callback;
}

void periodic_callbacks__1Hz_Stub(CMOCK_periodic_callbacks__1Hz_CALLBACK Callback)
{
  Mock.periodic_callbacks__1Hz_IgnoreBool = (int)0;
  Mock.periodic_callbacks__1Hz_CallbackBool = (int)0;
  Mock.periodic_callbacks__1Hz_CallbackFunctionPointer = Callback;
}

void periodic_callbacks__1Hz_CMockExpectAndThrow(UNITY_LINE_TYPE cmock_line, uint32_t callback_count, CEXCEPTION_T cmock_to_throw)
{
  CMOCK_MEM_INDEX_TYPE cmock_guts_index = CMock_Guts_MemNew(sizeof(CMOCK_periodic_callbacks__1Hz_CALL_INSTANCE));
  CMOCK_periodic_callbacks__1Hz_CALL_INSTANCE* cmock_call_instance = (CMOCK_periodic_callbacks__1Hz_CALL_INSTANCE*)CMock_Guts_GetAddressFor(cmock_guts_index);
  UNITY_TEST_ASSERT_NOT_NULL(cmock_call_instance, cmock_line, CMockStringOutOfMemory);
  memset(cmock_call_instance, 0, sizeof(*cmock_call_instance));
  Mock.periodic_callbacks__1Hz_CallInstance = CMock_Guts_MemChain(Mock.periodic_callbacks__1Hz_CallInstance, cmock_guts_index);
  Mock.periodic_callbacks__1Hz_IgnoreBool = (int)0;
  cmock_call_instance->LineNumber = cmock_line;
  cmock_call_instance->ExceptionToThrow = CEXCEPTION_NONE;
  cmock_call_instance->ExpectAnyArgsBool = (int)0;
  CMockExpectParameters_periodic_callbacks__1Hz(cmock_call_instance, callback_count);
  cmock_call_instance->ExceptionToThrow = cmock_to_throw;
}

void periodic_callbacks__1Hz_CMockIgnoreArg_callback_count(UNITY_LINE_TYPE cmock_line)
{
  CMOCK_periodic_callbacks__1Hz_CALL_INSTANCE* cmock_call_instance = (CMOCK_periodic_callbacks__1Hz_CALL_INSTANCE*)CMock_Guts_GetAddressFor(CMock_Guts_MemEndOfChain(Mock.periodic_callbacks__1Hz_CallInstance));
  UNITY_TEST_ASSERT_NOT_NULL(cmock_call_instance, cmock_line, CMockStringIgnPreExp);
  cmock_call_instance->IgnoreArg_callback_count = 1;
}

void periodic_callbacks__10Hz(uint32_t callback_count)
{
  UNITY_LINE_TYPE cmock_line = TEST_LINE_NUM;
  CMOCK_periodic_callbacks__10Hz_CALL_INSTANCE* cmock_call_instance;
  UNITY_SET_DETAIL(CMockString_periodic_callbacks__10Hz);
  cmock_call_instance = (CMOCK_periodic_callbacks__10Hz_CALL_INSTANCE*)CMock_Guts_GetAddressFor(Mock.periodic_callbacks__10Hz_CallInstance);
  Mock.periodic_callbacks__10Hz_CallInstance = CMock_Guts_MemNext(Mock.periodic_callbacks__10Hz_CallInstance);
  if (Mock.periodic_callbacks__10Hz_IgnoreBool)
  {
    UNITY_CLR_DETAILS();
    return;
  }
  if (!Mock.periodic_callbacks__10Hz_CallbackBool &&
      Mock.periodic_callbacks__10Hz_CallbackFunctionPointer != NULL)
  {
    Mock.periodic_callbacks__10Hz_CallbackFunctionPointer(callback_count, Mock.periodic_callbacks__10Hz_CallbackCalls++);
    UNITY_CLR_DETAILS();
    return;
  }
  UNITY_TEST_ASSERT_NOT_NULL(cmock_call_instance, cmock_line, CMockStringCalledMore);
  cmock_line = cmock_call_instance->LineNumber;
  if (!cmock_call_instance->ExpectAnyArgsBool)
  {
  if (!cmock_call_instance->IgnoreArg_callback_count)
  {
    UNITY_SET_DETAILS(CMockString_periodic_callbacks__10Hz,CMockString_callback_count);
    if (cmock_call_instance->Expected_callback_count != callback_count) {
    UNITY_TEST_ASSERT_EQUAL_HEX32(cmock_call_instance->Expected_callback_count, callback_count, cmock_line, CMockStringMismatch);
      }
  }
  }
  if (Mock.periodic_callbacks__10Hz_CallbackFunctionPointer != NULL)
  {
    Mock.periodic_callbacks__10Hz_CallbackFunctionPointer(callback_count, Mock.periodic_callbacks__10Hz_CallbackCalls++);
  }
  if (cmock_call_instance->ExceptionToThrow != CEXCEPTION_NONE)
  {
    UNITY_CLR_DETAILS();
    Throw(cmock_call_instance->ExceptionToThrow);
  }
  UNITY_CLR_DETAILS();
}

void CMockExpectParameters_periodic_callbacks__10Hz(CMOCK_periodic_callbacks__10Hz_CALL_INSTANCE* cmock_call_instance, uint32_t callback_count);
void CMockExpectParameters_periodic_callbacks__10Hz(CMOCK_periodic_callbacks__10Hz_CALL_INSTANCE* cmock_call_instance, uint32_t callback_count)
{
  cmock_call_instance->Expected_callback_count = callback_count;
  cmock_call_instance->IgnoreArg_callback_count = 0;
}

void periodic_callbacks__10Hz_CMockIgnore(void)
{
  Mock.periodic_callbacks__10Hz_IgnoreBool = (int)1;
}

void periodic_callbacks__10Hz_CMockExpectAnyArgs(UNITY_LINE_TYPE cmock_line)
{
  CMOCK_MEM_INDEX_TYPE cmock_guts_index = CMock_Guts_MemNew(sizeof(CMOCK_periodic_callbacks__10Hz_CALL_INSTANCE));
  CMOCK_periodic_callbacks__10Hz_CALL_INSTANCE* cmock_call_instance = (CMOCK_periodic_callbacks__10Hz_CALL_INSTANCE*)CMock_Guts_GetAddressFor(cmock_guts_index);
  UNITY_TEST_ASSERT_NOT_NULL(cmock_call_instance, cmock_line, CMockStringOutOfMemory);
  memset(cmock_call_instance, 0, sizeof(*cmock_call_instance));
  Mock.periodic_callbacks__10Hz_CallInstance = CMock_Guts_MemChain(Mock.periodic_callbacks__10Hz_CallInstance, cmock_guts_index);
  Mock.periodic_callbacks__10Hz_IgnoreBool = (int)0;
  cmock_call_instance->LineNumber = cmock_line;
  cmock_call_instance->ExceptionToThrow = CEXCEPTION_NONE;
  cmock_call_instance->ExpectAnyArgsBool = (int)0;
  cmock_call_instance->ExpectAnyArgsBool = (int)1;
}

void periodic_callbacks__10Hz_CMockExpect(UNITY_LINE_TYPE cmock_line, uint32_t callback_count)
{
  CMOCK_MEM_INDEX_TYPE cmock_guts_index = CMock_Guts_MemNew(sizeof(CMOCK_periodic_callbacks__10Hz_CALL_INSTANCE));
  CMOCK_periodic_callbacks__10Hz_CALL_INSTANCE* cmock_call_instance = (CMOCK_periodic_callbacks__10Hz_CALL_INSTANCE*)CMock_Guts_GetAddressFor(cmock_guts_index);
  UNITY_TEST_ASSERT_NOT_NULL(cmock_call_instance, cmock_line, CMockStringOutOfMemory);
  memset(cmock_call_instance, 0, sizeof(*cmock_call_instance));
  Mock.periodic_callbacks__10Hz_CallInstance = CMock_Guts_MemChain(Mock.periodic_callbacks__10Hz_CallInstance, cmock_guts_index);
  Mock.periodic_callbacks__10Hz_IgnoreBool = (int)0;
  cmock_call_instance->LineNumber = cmock_line;
  cmock_call_instance->ExceptionToThrow = CEXCEPTION_NONE;
  cmock_call_instance->ExpectAnyArgsBool = (int)0;
  CMockExpectParameters_periodic_callbacks__10Hz(cmock_call_instance, callback_count);
}

void periodic_callbacks__10Hz_AddCallback(CMOCK_periodic_callbacks__10Hz_CALLBACK Callback)
{
  Mock.periodic_callbacks__10Hz_IgnoreBool = (int)0;
  Mock.periodic_callbacks__10Hz_CallbackBool = (int)1;
  Mock.periodic_callbacks__10Hz_CallbackFunctionPointer = Callback;
}

void periodic_callbacks__10Hz_Stub(CMOCK_periodic_callbacks__10Hz_CALLBACK Callback)
{
  Mock.periodic_callbacks__10Hz_IgnoreBool = (int)0;
  Mock.periodic_callbacks__10Hz_CallbackBool = (int)0;
  Mock.periodic_callbacks__10Hz_CallbackFunctionPointer = Callback;
}

void periodic_callbacks__10Hz_CMockExpectAndThrow(UNITY_LINE_TYPE cmock_line, uint32_t callback_count, CEXCEPTION_T cmock_to_throw)
{
  CMOCK_MEM_INDEX_TYPE cmock_guts_index = CMock_Guts_MemNew(sizeof(CMOCK_periodic_callbacks__10Hz_CALL_INSTANCE));
  CMOCK_periodic_callbacks__10Hz_CALL_INSTANCE* cmock_call_instance = (CMOCK_periodic_callbacks__10Hz_CALL_INSTANCE*)CMock_Guts_GetAddressFor(cmock_guts_index);
  UNITY_TEST_ASSERT_NOT_NULL(cmock_call_instance, cmock_line, CMockStringOutOfMemory);
  memset(cmock_call_instance, 0, sizeof(*cmock_call_instance));
  Mock.periodic_callbacks__10Hz_CallInstance = CMock_Guts_MemChain(Mock.periodic_callbacks__10Hz_CallInstance, cmock_guts_index);
  Mock.periodic_callbacks__10Hz_IgnoreBool = (int)0;
  cmock_call_instance->LineNumber = cmock_line;
  cmock_call_instance->ExceptionToThrow = CEXCEPTION_NONE;
  cmock_call_instance->ExpectAnyArgsBool = (int)0;
  CMockExpectParameters_periodic_callbacks__10Hz(cmock_call_instance, callback_count);
  cmock_call_instance->ExceptionToThrow = cmock_to_throw;
}

void periodic_callbacks__10Hz_CMockIgnoreArg_callback_count(UNITY_LINE_TYPE cmock_line)
{
  CMOCK_periodic_callbacks__10Hz_CALL_INSTANCE* cmock_call_instance = (CMOCK_periodic_callbacks__10Hz_CALL_INSTANCE*)CMock_Guts_GetAddressFor(CMock_Guts_MemEndOfChain(Mock.periodic_callbacks__10Hz_CallInstance));
  UNITY_TEST_ASSERT_NOT_NULL(cmock_call_instance, cmock_line, CMockStringIgnPreExp);
  cmock_call_instance->IgnoreArg_callback_count = 1;
}

void periodic_callbacks__100Hz(uint32_t callback_count)
{
  UNITY_LINE_TYPE cmock_line = TEST_LINE_NUM;
  CMOCK_periodic_callbacks__100Hz_CALL_INSTANCE* cmock_call_instance;
  UNITY_SET_DETAIL(CMockString_periodic_callbacks__100Hz);
  cmock_call_instance = (CMOCK_periodic_callbacks__100Hz_CALL_INSTANCE*)CMock_Guts_GetAddressFor(Mock.periodic_callbacks__100Hz_CallInstance);
  Mock.periodic_callbacks__100Hz_CallInstance = CMock_Guts_MemNext(Mock.periodic_callbacks__100Hz_CallInstance);
  if (Mock.periodic_callbacks__100Hz_IgnoreBool)
  {
    UNITY_CLR_DETAILS();
    return;
  }
  if (!Mock.periodic_callbacks__100Hz_CallbackBool &&
      Mock.periodic_callbacks__100Hz_CallbackFunctionPointer != NULL)
  {
    Mock.periodic_callbacks__100Hz_CallbackFunctionPointer(callback_count, Mock.periodic_callbacks__100Hz_CallbackCalls++);
    UNITY_CLR_DETAILS();
    return;
  }
  UNITY_TEST_ASSERT_NOT_NULL(cmock_call_instance, cmock_line, CMockStringCalledMore);
  cmock_line = cmock_call_instance->LineNumber;
  if (!cmock_call_instance->ExpectAnyArgsBool)
  {
  if (!cmock_call_instance->IgnoreArg_callback_count)
  {
    UNITY_SET_DETAILS(CMockString_periodic_callbacks__100Hz,CMockString_callback_count);
    if (cmock_call_instance->Expected_callback_count != callback_count) {
    UNITY_TEST_ASSERT_EQUAL_HEX32(cmock_call_instance->Expected_callback_count, callback_count, cmock_line, CMockStringMismatch);
      }
  }
  }
  if (Mock.periodic_callbacks__100Hz_CallbackFunctionPointer != NULL)
  {
    Mock.periodic_callbacks__100Hz_CallbackFunctionPointer(callback_count, Mock.periodic_callbacks__100Hz_CallbackCalls++);
  }
  if (cmock_call_instance->ExceptionToThrow != CEXCEPTION_NONE)
  {
    UNITY_CLR_DETAILS();
    Throw(cmock_call_instance->ExceptionToThrow);
  }
  UNITY_CLR_DETAILS();
}

void CMockExpectParameters_periodic_callbacks__100Hz(CMOCK_periodic_callbacks__100Hz_CALL_INSTANCE* cmock_call_instance, uint32_t callback_count);
void CMockExpectParameters_periodic_callbacks__100Hz(CMOCK_periodic_callbacks__100Hz_CALL_INSTANCE* cmock_call_instance, uint32_t callback_count)
{
  cmock_call_instance->Expected_callback_count = callback_count;
  cmock_call_instance->IgnoreArg_callback_count = 0;
}

void periodic_callbacks__100Hz_CMockIgnore(void)
{
  Mock.periodic_callbacks__100Hz_IgnoreBool = (int)1;
}

void periodic_callbacks__100Hz_CMockExpectAnyArgs(UNITY_LINE_TYPE cmock_line)
{
  CMOCK_MEM_INDEX_TYPE cmock_guts_index = CMock_Guts_MemNew(sizeof(CMOCK_periodic_callbacks__100Hz_CALL_INSTANCE));
  CMOCK_periodic_callbacks__100Hz_CALL_INSTANCE* cmock_call_instance = (CMOCK_periodic_callbacks__100Hz_CALL_INSTANCE*)CMock_Guts_GetAddressFor(cmock_guts_index);
  UNITY_TEST_ASSERT_NOT_NULL(cmock_call_instance, cmock_line, CMockStringOutOfMemory);
  memset(cmock_call_instance, 0, sizeof(*cmock_call_instance));
  Mock.periodic_callbacks__100Hz_CallInstance = CMock_Guts_MemChain(Mock.periodic_callbacks__100Hz_CallInstance, cmock_guts_index);
  Mock.periodic_callbacks__100Hz_IgnoreBool = (int)0;
  cmock_call_instance->LineNumber = cmock_line;
  cmock_call_instance->ExceptionToThrow = CEXCEPTION_NONE;
  cmock_call_instance->ExpectAnyArgsBool = (int)0;
  cmock_call_instance->ExpectAnyArgsBool = (int)1;
}

void periodic_callbacks__100Hz_CMockExpect(UNITY_LINE_TYPE cmock_line, uint32_t callback_count)
{
  CMOCK_MEM_INDEX_TYPE cmock_guts_index = CMock_Guts_MemNew(sizeof(CMOCK_periodic_callbacks__100Hz_CALL_INSTANCE));
  CMOCK_periodic_callbacks__100Hz_CALL_INSTANCE* cmock_call_instance = (CMOCK_periodic_callbacks__100Hz_CALL_INSTANCE*)CMock_Guts_GetAddressFor(cmock_guts_index);
  UNITY_TEST_ASSERT_NOT_NULL(cmock_call_instance, cmock_line, CMockStringOutOfMemory);
  memset(cmock_call_instance, 0, sizeof(*cmock_call_instance));
  Mock.periodic_callbacks__100Hz_CallInstance = CMock_Guts_MemChain(Mock.periodic_callbacks__100Hz_CallInstance, cmock_guts_index);
  Mock.periodic_callbacks__100Hz_IgnoreBool = (int)0;
  cmock_call_instance->LineNumber = cmock_line;
  cmock_call_instance->ExceptionToThrow = CEXCEPTION_NONE;
  cmock_call_instance->ExpectAnyArgsBool = (int)0;
  CMockExpectParameters_periodic_callbacks__100Hz(cmock_call_instance, callback_count);
}

void periodic_callbacks__100Hz_AddCallback(CMOCK_periodic_callbacks__100Hz_CALLBACK Callback)
{
  Mock.periodic_callbacks__100Hz_IgnoreBool = (int)0;
  Mock.periodic_callbacks__100Hz_CallbackBool = (int)1;
  Mock.periodic_callbacks__100Hz_CallbackFunctionPointer = Callback;
}

void periodic_callbacks__100Hz_Stub(CMOCK_periodic_callbacks__100Hz_CALLBACK Callback)
{
  Mock.periodic_callbacks__100Hz_IgnoreBool = (int)0;
  Mock.periodic_callbacks__100Hz_CallbackBool = (int)0;
  Mock.periodic_callbacks__100Hz_CallbackFunctionPointer = Callback;
}

void periodic_callbacks__100Hz_CMockExpectAndThrow(UNITY_LINE_TYPE cmock_line, uint32_t callback_count, CEXCEPTION_T cmock_to_throw)
{
  CMOCK_MEM_INDEX_TYPE cmock_guts_index = CMock_Guts_MemNew(sizeof(CMOCK_periodic_callbacks__100Hz_CALL_INSTANCE));
  CMOCK_periodic_callbacks__100Hz_CALL_INSTANCE* cmock_call_instance = (CMOCK_periodic_callbacks__100Hz_CALL_INSTANCE*)CMock_Guts_GetAddressFor(cmock_guts_index);
  UNITY_TEST_ASSERT_NOT_NULL(cmock_call_instance, cmock_line, CMockStringOutOfMemory);
  memset(cmock_call_instance, 0, sizeof(*cmock_call_instance));
  Mock.periodic_callbacks__100Hz_CallInstance = CMock_Guts_MemChain(Mock.periodic_callbacks__100Hz_CallInstance, cmock_guts_index);
  Mock.periodic_callbacks__100Hz_IgnoreBool = (int)0;
  cmock_call_instance->LineNumber = cmock_line;
  cmock_call_instance->ExceptionToThrow = CEXCEPTION_NONE;
  cmock_call_instance->ExpectAnyArgsBool = (int)0;
  CMockExpectParameters_periodic_callbacks__100Hz(cmock_call_instance, callback_count);
  cmock_call_instance->ExceptionToThrow = cmock_to_throw;
}

void periodic_callbacks__100Hz_CMockIgnoreArg_callback_count(UNITY_LINE_TYPE cmock_line)
{
  CMOCK_periodic_callbacks__100Hz_CALL_INSTANCE* cmock_call_instance = (CMOCK_periodic_callbacks__100Hz_CALL_INSTANCE*)CMock_Guts_GetAddressFor(CMock_Guts_MemEndOfChain(Mock.periodic_callbacks__100Hz_CallInstance));
  UNITY_TEST_ASSERT_NOT_NULL(cmock_call_instance, cmock_line, CMockStringIgnPreExp);
  cmock_call_instance->IgnoreArg_callback_count = 1;
}

void periodic_callbacks__1000Hz(uint32_t callback_count)
{
  UNITY_LINE_TYPE cmock_line = TEST_LINE_NUM;
  CMOCK_periodic_callbacks__1000Hz_CALL_INSTANCE* cmock_call_instance;
  UNITY_SET_DETAIL(CMockString_periodic_callbacks__1000Hz);
  cmock_call_instance = (CMOCK_periodic_callbacks__1000Hz_CALL_INSTANCE*)CMock_Guts_GetAddressFor(Mock.periodic_callbacks__1000Hz_CallInstance);
  Mock.periodic_callbacks__1000Hz_CallInstance = CMock_Guts_MemNext(Mock.periodic_callbacks__1000Hz_CallInstance);
  if (Mock.periodic_callbacks__1000Hz_IgnoreBool)
  {
    UNITY_CLR_DETAILS();
    return;
  }
  if (!Mock.periodic_callbacks__1000Hz_CallbackBool &&
      Mock.periodic_callbacks__1000Hz_CallbackFunctionPointer != NULL)
  {
    Mock.periodic_callbacks__1000Hz_CallbackFunctionPointer(callback_count, Mock.periodic_callbacks__1000Hz_CallbackCalls++);
    UNITY_CLR_DETAILS();
    return;
  }
  UNITY_TEST_ASSERT_NOT_NULL(cmock_call_instance, cmock_line, CMockStringCalledMore);
  cmock_line = cmock_call_instance->LineNumber;
  if (!cmock_call_instance->ExpectAnyArgsBool)
  {
  if (!cmock_call_instance->IgnoreArg_callback_count)
  {
    UNITY_SET_DETAILS(CMockString_periodic_callbacks__1000Hz,CMockString_callback_count);
    if (cmock_call_instance->Expected_callback_count != callback_count) {
    UNITY_TEST_ASSERT_EQUAL_HEX32(cmock_call_instance->Expected_callback_count, callback_count, cmock_line, CMockStringMismatch);
      }
  }
  }
  if (Mock.periodic_callbacks__1000Hz_CallbackFunctionPointer != NULL)
  {
    Mock.periodic_callbacks__1000Hz_CallbackFunctionPointer(callback_count, Mock.periodic_callbacks__1000Hz_CallbackCalls++);
  }
  if (cmock_call_instance->ExceptionToThrow != CEXCEPTION_NONE)
  {
    UNITY_CLR_DETAILS();
    Throw(cmock_call_instance->ExceptionToThrow);
  }
  UNITY_CLR_DETAILS();
}

void CMockExpectParameters_periodic_callbacks__1000Hz(CMOCK_periodic_callbacks__1000Hz_CALL_INSTANCE* cmock_call_instance, uint32_t callback_count);
void CMockExpectParameters_periodic_callbacks__1000Hz(CMOCK_periodic_callbacks__1000Hz_CALL_INSTANCE* cmock_call_instance, uint32_t callback_count)
{
  cmock_call_instance->Expected_callback_count = callback_count;
  cmock_call_instance->IgnoreArg_callback_count = 0;
}

void periodic_callbacks__1000Hz_CMockIgnore(void)
{
  Mock.periodic_callbacks__1000Hz_IgnoreBool = (int)1;
}

void periodic_callbacks__1000Hz_CMockExpectAnyArgs(UNITY_LINE_TYPE cmock_line)
{
  CMOCK_MEM_INDEX_TYPE cmock_guts_index = CMock_Guts_MemNew(sizeof(CMOCK_periodic_callbacks__1000Hz_CALL_INSTANCE));
  CMOCK_periodic_callbacks__1000Hz_CALL_INSTANCE* cmock_call_instance = (CMOCK_periodic_callbacks__1000Hz_CALL_INSTANCE*)CMock_Guts_GetAddressFor(cmock_guts_index);
  UNITY_TEST_ASSERT_NOT_NULL(cmock_call_instance, cmock_line, CMockStringOutOfMemory);
  memset(cmock_call_instance, 0, sizeof(*cmock_call_instance));
  Mock.periodic_callbacks__1000Hz_CallInstance = CMock_Guts_MemChain(Mock.periodic_callbacks__1000Hz_CallInstance, cmock_guts_index);
  Mock.periodic_callbacks__1000Hz_IgnoreBool = (int)0;
  cmock_call_instance->LineNumber = cmock_line;
  cmock_call_instance->ExceptionToThrow = CEXCEPTION_NONE;
  cmock_call_instance->ExpectAnyArgsBool = (int)0;
  cmock_call_instance->ExpectAnyArgsBool = (int)1;
}

void periodic_callbacks__1000Hz_CMockExpect(UNITY_LINE_TYPE cmock_line, uint32_t callback_count)
{
  CMOCK_MEM_INDEX_TYPE cmock_guts_index = CMock_Guts_MemNew(sizeof(CMOCK_periodic_callbacks__1000Hz_CALL_INSTANCE));
  CMOCK_periodic_callbacks__1000Hz_CALL_INSTANCE* cmock_call_instance = (CMOCK_periodic_callbacks__1000Hz_CALL_INSTANCE*)CMock_Guts_GetAddressFor(cmock_guts_index);
  UNITY_TEST_ASSERT_NOT_NULL(cmock_call_instance, cmock_line, CMockStringOutOfMemory);
  memset(cmock_call_instance, 0, sizeof(*cmock_call_instance));
  Mock.periodic_callbacks__1000Hz_CallInstance = CMock_Guts_MemChain(Mock.periodic_callbacks__1000Hz_CallInstance, cmock_guts_index);
  Mock.periodic_callbacks__1000Hz_IgnoreBool = (int)0;
  cmock_call_instance->LineNumber = cmock_line;
  cmock_call_instance->ExceptionToThrow = CEXCEPTION_NONE;
  cmock_call_instance->ExpectAnyArgsBool = (int)0;
  CMockExpectParameters_periodic_callbacks__1000Hz(cmock_call_instance, callback_count);
}

void periodic_callbacks__1000Hz_AddCallback(CMOCK_periodic_callbacks__1000Hz_CALLBACK Callback)
{
  Mock.periodic_callbacks__1000Hz_IgnoreBool = (int)0;
  Mock.periodic_callbacks__1000Hz_CallbackBool = (int)1;
  Mock.periodic_callbacks__1000Hz_CallbackFunctionPointer = Callback;
}

void periodic_callbacks__1000Hz_Stub(CMOCK_periodic_callbacks__1000Hz_CALLBACK Callback)
{
  Mock.periodic_callbacks__1000Hz_IgnoreBool = (int)0;
  Mock.periodic_callbacks__1000Hz_CallbackBool = (int)0;
  Mock.periodic_callbacks__1000Hz_CallbackFunctionPointer = Callback;
}

void periodic_callbacks__1000Hz_CMockExpectAndThrow(UNITY_LINE_TYPE cmock_line, uint32_t callback_count, CEXCEPTION_T cmock_to_throw)
{
  CMOCK_MEM_INDEX_TYPE cmock_guts_index = CMock_Guts_MemNew(sizeof(CMOCK_periodic_callbacks__1000Hz_CALL_INSTANCE));
  CMOCK_periodic_callbacks__1000Hz_CALL_INSTANCE* cmock_call_instance = (CMOCK_periodic_callbacks__1000Hz_CALL_INSTANCE*)CMock_Guts_GetAddressFor(cmock_guts_index);
  UNITY_TEST_ASSERT_NOT_NULL(cmock_call_instance, cmock_line, CMockStringOutOfMemory);
  memset(cmock_call_instance, 0, sizeof(*cmock_call_instance));
  Mock.periodic_callbacks__1000Hz_CallInstance = CMock_Guts_MemChain(Mock.periodic_callbacks__1000Hz_CallInstance, cmock_guts_index);
  Mock.periodic_callbacks__1000Hz_IgnoreBool = (int)0;
  cmock_call_instance->LineNumber = cmock_line;
  cmock_call_instance->ExceptionToThrow = CEXCEPTION_NONE;
  cmock_call_instance->ExpectAnyArgsBool = (int)0;
  CMockExpectParameters_periodic_callbacks__1000Hz(cmock_call_instance, callback_count);
  cmock_call_instance->ExceptionToThrow = cmock_to_throw;
}

void periodic_callbacks__1000Hz_CMockIgnoreArg_callback_count(UNITY_LINE_TYPE cmock_line)
{
  CMOCK_periodic_callbacks__1000Hz_CALL_INSTANCE* cmock_call_instance = (CMOCK_periodic_callbacks__1000Hz_CALL_INSTANCE*)CMock_Guts_GetAddressFor(CMock_Guts_MemEndOfChain(Mock.periodic_callbacks__1000Hz_CallInstance));
  UNITY_TEST_ASSERT_NOT_NULL(cmock_call_instance, cmock_line, CMockStringIgnPreExp);
  cmock_call_instance->IgnoreArg_callback_count = 1;
}

