/* AUTOGENERATED FILE. DO NOT EDIT. */

/*=======Automagically Detected Files To Include=====*/
#include "unity.h"
#include "cmock.h"
#include "periodic_callbacks.h"
#include <stdio.h>
#include <string.h>
#include "Mockboard_io.h"
#include "Mockgpio.h"

/*=======External Functions This Runner Calls=====*/
extern void setUp(void);
extern void tearDown(void);
extern void test__periodic_callbacks__initialize(void);
extern void test__periodic_callbacks__1Hz(void);


/*=======Mock Management=====*/
static void CMock_Init(void)
{
  Mockboard_io_Init();
  Mockgpio_Init();
}
static void CMock_Verify(void)
{
  Mockboard_io_Verify();
  Mockgpio_Verify();
}
static void CMock_Destroy(void)
{
  Mockboard_io_Destroy();
  Mockgpio_Destroy();
}

/*=======Test Reset Options=====*/
void resetTest(void);
void resetTest(void)
{
  tearDown();
  CMock_Verify();
  CMock_Destroy();
  CMock_Init();
  setUp();
}
void verifyTest(void);
void verifyTest(void)
{
  CMock_Verify();
}
/*=======Test Runner Used To Run Each Test=====*/
static void run_test(UnityTestFunction func, const char* name, int line_num)
{
    Unity.CurrentTestName = name;
    Unity.CurrentTestLineNumber = line_num;
#ifdef UNITY_USE_COMMAND_LINE_ARGS
    if (!UnityTestMatches())
        return;
#endif
    Unity.NumberOfTests++;
    UNITY_CLR_DETAILS();
    UNITY_EXEC_TIME_START();
    CMock_Init();
    if (TEST_PROTECT())
    {

            setUp();
            func();

    }
    if (TEST_PROTECT())
    {
        tearDown();
        CMock_Verify();
    }
    CMock_Destroy();
    UNITY_EXEC_TIME_STOP();
    UnityConcludeTest();
}


/*=======MAIN=====*/
int main(void)
{
  UnityBegin("projects\\lpc40xx_freertos\\l5_application\\periodics\\test\\test_periodic_callbacks.c");
  run_test(test__periodic_callbacks__initialize, "test__periodic_callbacks__initialize", 19);
  run_test(test__periodic_callbacks__1Hz, "test__periodic_callbacks__1Hz", 21);

  CMock_Guts_MemFreeFinal();
  return UnityEnd();
}
