/* AUTOGENERATED FILE. DO NOT EDIT. */
#include <string.h>
#include <stdlib.h>
#include <setjmp.h>
#include "cmock.h"
#include "Mockboard_io.h"

static const char* CMockString_board_io__get_led0 = "board_io__get_led0";
static const char* CMockString_board_io__get_led1 = "board_io__get_led1";
static const char* CMockString_board_io__get_led2 = "board_io__get_led2";
static const char* CMockString_board_io__get_led3 = "board_io__get_led3";
static const char* CMockString_board_io__get_sw0 = "board_io__get_sw0";
static const char* CMockString_board_io__get_sw1 = "board_io__get_sw1";
static const char* CMockString_board_io__get_sw2 = "board_io__get_sw2";
static const char* CMockString_board_io__get_sw3 = "board_io__get_sw3";
static const char* CMockString_board_io__initialize = "board_io__initialize";
static const char* CMockString_board_io__sd_card_cs = "board_io__sd_card_cs";
static const char* CMockString_board_io__sd_card_ds = "board_io__sd_card_ds";
static const char* CMockString_board_io__sd_card_is_present = "board_io__sd_card_is_present";

typedef struct _CMOCK_board_io__initialize_CALL_INSTANCE
{
  UNITY_LINE_TYPE LineNumber;
  int ExpectAnyArgsBool;
  CEXCEPTION_T ExceptionToThrow;

} CMOCK_board_io__initialize_CALL_INSTANCE;

typedef struct _CMOCK_board_io__sd_card_cs_CALL_INSTANCE
{
  UNITY_LINE_TYPE LineNumber;
  int ExpectAnyArgsBool;
  CEXCEPTION_T ExceptionToThrow;

} CMOCK_board_io__sd_card_cs_CALL_INSTANCE;

typedef struct _CMOCK_board_io__sd_card_ds_CALL_INSTANCE
{
  UNITY_LINE_TYPE LineNumber;
  int ExpectAnyArgsBool;
  CEXCEPTION_T ExceptionToThrow;

} CMOCK_board_io__sd_card_ds_CALL_INSTANCE;

typedef struct _CMOCK_board_io__sd_card_is_present_CALL_INSTANCE
{
  UNITY_LINE_TYPE LineNumber;
  int ExpectAnyArgsBool;
  bool ReturnVal;
  CEXCEPTION_T ExceptionToThrow;

} CMOCK_board_io__sd_card_is_present_CALL_INSTANCE;

typedef struct _CMOCK_board_io__get_led0_CALL_INSTANCE
{
  UNITY_LINE_TYPE LineNumber;
  int ExpectAnyArgsBool;
  gpio_s ReturnVal;
  CEXCEPTION_T ExceptionToThrow;

} CMOCK_board_io__get_led0_CALL_INSTANCE;

typedef struct _CMOCK_board_io__get_led1_CALL_INSTANCE
{
  UNITY_LINE_TYPE LineNumber;
  int ExpectAnyArgsBool;
  gpio_s ReturnVal;
  CEXCEPTION_T ExceptionToThrow;

} CMOCK_board_io__get_led1_CALL_INSTANCE;

typedef struct _CMOCK_board_io__get_led2_CALL_INSTANCE
{
  UNITY_LINE_TYPE LineNumber;
  int ExpectAnyArgsBool;
  gpio_s ReturnVal;
  CEXCEPTION_T ExceptionToThrow;

} CMOCK_board_io__get_led2_CALL_INSTANCE;

typedef struct _CMOCK_board_io__get_led3_CALL_INSTANCE
{
  UNITY_LINE_TYPE LineNumber;
  int ExpectAnyArgsBool;
  gpio_s ReturnVal;
  CEXCEPTION_T ExceptionToThrow;

} CMOCK_board_io__get_led3_CALL_INSTANCE;

typedef struct _CMOCK_board_io__get_sw0_CALL_INSTANCE
{
  UNITY_LINE_TYPE LineNumber;
  int ExpectAnyArgsBool;
  gpio_s ReturnVal;
  CEXCEPTION_T ExceptionToThrow;

} CMOCK_board_io__get_sw0_CALL_INSTANCE;

typedef struct _CMOCK_board_io__get_sw1_CALL_INSTANCE
{
  UNITY_LINE_TYPE LineNumber;
  int ExpectAnyArgsBool;
  gpio_s ReturnVal;
  CEXCEPTION_T ExceptionToThrow;

} CMOCK_board_io__get_sw1_CALL_INSTANCE;

typedef struct _CMOCK_board_io__get_sw2_CALL_INSTANCE
{
  UNITY_LINE_TYPE LineNumber;
  int ExpectAnyArgsBool;
  gpio_s ReturnVal;
  CEXCEPTION_T ExceptionToThrow;

} CMOCK_board_io__get_sw2_CALL_INSTANCE;

typedef struct _CMOCK_board_io__get_sw3_CALL_INSTANCE
{
  UNITY_LINE_TYPE LineNumber;
  int ExpectAnyArgsBool;
  gpio_s ReturnVal;
  CEXCEPTION_T ExceptionToThrow;

} CMOCK_board_io__get_sw3_CALL_INSTANCE;

static struct Mockboard_ioInstance
{
  int board_io__initialize_IgnoreBool;
  int board_io__initialize_CallbackBool;
  CMOCK_board_io__initialize_CALLBACK board_io__initialize_CallbackFunctionPointer;
  int board_io__initialize_CallbackCalls;
  CMOCK_MEM_INDEX_TYPE board_io__initialize_CallInstance;
  int board_io__sd_card_cs_IgnoreBool;
  int board_io__sd_card_cs_CallbackBool;
  CMOCK_board_io__sd_card_cs_CALLBACK board_io__sd_card_cs_CallbackFunctionPointer;
  int board_io__sd_card_cs_CallbackCalls;
  CMOCK_MEM_INDEX_TYPE board_io__sd_card_cs_CallInstance;
  int board_io__sd_card_ds_IgnoreBool;
  int board_io__sd_card_ds_CallbackBool;
  CMOCK_board_io__sd_card_ds_CALLBACK board_io__sd_card_ds_CallbackFunctionPointer;
  int board_io__sd_card_ds_CallbackCalls;
  CMOCK_MEM_INDEX_TYPE board_io__sd_card_ds_CallInstance;
  int board_io__sd_card_is_present_IgnoreBool;
  bool board_io__sd_card_is_present_FinalReturn;
  int board_io__sd_card_is_present_CallbackBool;
  CMOCK_board_io__sd_card_is_present_CALLBACK board_io__sd_card_is_present_CallbackFunctionPointer;
  int board_io__sd_card_is_present_CallbackCalls;
  CMOCK_MEM_INDEX_TYPE board_io__sd_card_is_present_CallInstance;
  int board_io__get_led0_IgnoreBool;
  gpio_s board_io__get_led0_FinalReturn;
  int board_io__get_led0_CallbackBool;
  CMOCK_board_io__get_led0_CALLBACK board_io__get_led0_CallbackFunctionPointer;
  int board_io__get_led0_CallbackCalls;
  CMOCK_MEM_INDEX_TYPE board_io__get_led0_CallInstance;
  int board_io__get_led1_IgnoreBool;
  gpio_s board_io__get_led1_FinalReturn;
  int board_io__get_led1_CallbackBool;
  CMOCK_board_io__get_led1_CALLBACK board_io__get_led1_CallbackFunctionPointer;
  int board_io__get_led1_CallbackCalls;
  CMOCK_MEM_INDEX_TYPE board_io__get_led1_CallInstance;
  int board_io__get_led2_IgnoreBool;
  gpio_s board_io__get_led2_FinalReturn;
  int board_io__get_led2_CallbackBool;
  CMOCK_board_io__get_led2_CALLBACK board_io__get_led2_CallbackFunctionPointer;
  int board_io__get_led2_CallbackCalls;
  CMOCK_MEM_INDEX_TYPE board_io__get_led2_CallInstance;
  int board_io__get_led3_IgnoreBool;
  gpio_s board_io__get_led3_FinalReturn;
  int board_io__get_led3_CallbackBool;
  CMOCK_board_io__get_led3_CALLBACK board_io__get_led3_CallbackFunctionPointer;
  int board_io__get_led3_CallbackCalls;
  CMOCK_MEM_INDEX_TYPE board_io__get_led3_CallInstance;
  int board_io__get_sw0_IgnoreBool;
  gpio_s board_io__get_sw0_FinalReturn;
  int board_io__get_sw0_CallbackBool;
  CMOCK_board_io__get_sw0_CALLBACK board_io__get_sw0_CallbackFunctionPointer;
  int board_io__get_sw0_CallbackCalls;
  CMOCK_MEM_INDEX_TYPE board_io__get_sw0_CallInstance;
  int board_io__get_sw1_IgnoreBool;
  gpio_s board_io__get_sw1_FinalReturn;
  int board_io__get_sw1_CallbackBool;
  CMOCK_board_io__get_sw1_CALLBACK board_io__get_sw1_CallbackFunctionPointer;
  int board_io__get_sw1_CallbackCalls;
  CMOCK_MEM_INDEX_TYPE board_io__get_sw1_CallInstance;
  int board_io__get_sw2_IgnoreBool;
  gpio_s board_io__get_sw2_FinalReturn;
  int board_io__get_sw2_CallbackBool;
  CMOCK_board_io__get_sw2_CALLBACK board_io__get_sw2_CallbackFunctionPointer;
  int board_io__get_sw2_CallbackCalls;
  CMOCK_MEM_INDEX_TYPE board_io__get_sw2_CallInstance;
  int board_io__get_sw3_IgnoreBool;
  gpio_s board_io__get_sw3_FinalReturn;
  int board_io__get_sw3_CallbackBool;
  CMOCK_board_io__get_sw3_CALLBACK board_io__get_sw3_CallbackFunctionPointer;
  int board_io__get_sw3_CallbackCalls;
  CMOCK_MEM_INDEX_TYPE board_io__get_sw3_CallInstance;
} Mock;

extern jmp_buf AbortFrame;

void Mockboard_io_Verify(void)
{
  UNITY_LINE_TYPE cmock_line = TEST_LINE_NUM;
  CMOCK_MEM_INDEX_TYPE call_instance;
  call_instance = Mock.board_io__initialize_CallInstance;
  if (Mock.board_io__initialize_IgnoreBool)
    call_instance = CMOCK_GUTS_NONE;
  UNITY_SET_DETAIL(CMockString_board_io__initialize);
  UNITY_TEST_ASSERT(CMOCK_GUTS_NONE == call_instance, cmock_line, CMockStringCalledLess);
  UNITY_CLR_DETAILS();
  if (Mock.board_io__initialize_CallbackFunctionPointer != NULL)
    call_instance = CMOCK_GUTS_NONE;
  call_instance = Mock.board_io__sd_card_cs_CallInstance;
  if (Mock.board_io__sd_card_cs_IgnoreBool)
    call_instance = CMOCK_GUTS_NONE;
  UNITY_SET_DETAIL(CMockString_board_io__sd_card_cs);
  UNITY_TEST_ASSERT(CMOCK_GUTS_NONE == call_instance, cmock_line, CMockStringCalledLess);
  UNITY_CLR_DETAILS();
  if (Mock.board_io__sd_card_cs_CallbackFunctionPointer != NULL)
    call_instance = CMOCK_GUTS_NONE;
  call_instance = Mock.board_io__sd_card_ds_CallInstance;
  if (Mock.board_io__sd_card_ds_IgnoreBool)
    call_instance = CMOCK_GUTS_NONE;
  UNITY_SET_DETAIL(CMockString_board_io__sd_card_ds);
  UNITY_TEST_ASSERT(CMOCK_GUTS_NONE == call_instance, cmock_line, CMockStringCalledLess);
  UNITY_CLR_DETAILS();
  if (Mock.board_io__sd_card_ds_CallbackFunctionPointer != NULL)
    call_instance = CMOCK_GUTS_NONE;
  call_instance = Mock.board_io__sd_card_is_present_CallInstance;
  if (Mock.board_io__sd_card_is_present_IgnoreBool)
    call_instance = CMOCK_GUTS_NONE;
  UNITY_SET_DETAIL(CMockString_board_io__sd_card_is_present);
  UNITY_TEST_ASSERT(CMOCK_GUTS_NONE == call_instance, cmock_line, CMockStringCalledLess);
  UNITY_CLR_DETAILS();
  if (Mock.board_io__sd_card_is_present_CallbackFunctionPointer != NULL)
    call_instance = CMOCK_GUTS_NONE;
  call_instance = Mock.board_io__get_led0_CallInstance;
  if (Mock.board_io__get_led0_IgnoreBool)
    call_instance = CMOCK_GUTS_NONE;
  UNITY_SET_DETAIL(CMockString_board_io__get_led0);
  UNITY_TEST_ASSERT(CMOCK_GUTS_NONE == call_instance, cmock_line, CMockStringCalledLess);
  UNITY_CLR_DETAILS();
  if (Mock.board_io__get_led0_CallbackFunctionPointer != NULL)
    call_instance = CMOCK_GUTS_NONE;
  call_instance = Mock.board_io__get_led1_CallInstance;
  if (Mock.board_io__get_led1_IgnoreBool)
    call_instance = CMOCK_GUTS_NONE;
  UNITY_SET_DETAIL(CMockString_board_io__get_led1);
  UNITY_TEST_ASSERT(CMOCK_GUTS_NONE == call_instance, cmock_line, CMockStringCalledLess);
  UNITY_CLR_DETAILS();
  if (Mock.board_io__get_led1_CallbackFunctionPointer != NULL)
    call_instance = CMOCK_GUTS_NONE;
  call_instance = Mock.board_io__get_led2_CallInstance;
  if (Mock.board_io__get_led2_IgnoreBool)
    call_instance = CMOCK_GUTS_NONE;
  UNITY_SET_DETAIL(CMockString_board_io__get_led2);
  UNITY_TEST_ASSERT(CMOCK_GUTS_NONE == call_instance, cmock_line, CMockStringCalledLess);
  UNITY_CLR_DETAILS();
  if (Mock.board_io__get_led2_CallbackFunctionPointer != NULL)
    call_instance = CMOCK_GUTS_NONE;
  call_instance = Mock.board_io__get_led3_CallInstance;
  if (Mock.board_io__get_led3_IgnoreBool)
    call_instance = CMOCK_GUTS_NONE;
  UNITY_SET_DETAIL(CMockString_board_io__get_led3);
  UNITY_TEST_ASSERT(CMOCK_GUTS_NONE == call_instance, cmock_line, CMockStringCalledLess);
  UNITY_CLR_DETAILS();
  if (Mock.board_io__get_led3_CallbackFunctionPointer != NULL)
    call_instance = CMOCK_GUTS_NONE;
  call_instance = Mock.board_io__get_sw0_CallInstance;
  if (Mock.board_io__get_sw0_IgnoreBool)
    call_instance = CMOCK_GUTS_NONE;
  UNITY_SET_DETAIL(CMockString_board_io__get_sw0);
  UNITY_TEST_ASSERT(CMOCK_GUTS_NONE == call_instance, cmock_line, CMockStringCalledLess);
  UNITY_CLR_DETAILS();
  if (Mock.board_io__get_sw0_CallbackFunctionPointer != NULL)
    call_instance = CMOCK_GUTS_NONE;
  call_instance = Mock.board_io__get_sw1_CallInstance;
  if (Mock.board_io__get_sw1_IgnoreBool)
    call_instance = CMOCK_GUTS_NONE;
  UNITY_SET_DETAIL(CMockString_board_io__get_sw1);
  UNITY_TEST_ASSERT(CMOCK_GUTS_NONE == call_instance, cmock_line, CMockStringCalledLess);
  UNITY_CLR_DETAILS();
  if (Mock.board_io__get_sw1_CallbackFunctionPointer != NULL)
    call_instance = CMOCK_GUTS_NONE;
  call_instance = Mock.board_io__get_sw2_CallInstance;
  if (Mock.board_io__get_sw2_IgnoreBool)
    call_instance = CMOCK_GUTS_NONE;
  UNITY_SET_DETAIL(CMockString_board_io__get_sw2);
  UNITY_TEST_ASSERT(CMOCK_GUTS_NONE == call_instance, cmock_line, CMockStringCalledLess);
  UNITY_CLR_DETAILS();
  if (Mock.board_io__get_sw2_CallbackFunctionPointer != NULL)
    call_instance = CMOCK_GUTS_NONE;
  call_instance = Mock.board_io__get_sw3_CallInstance;
  if (Mock.board_io__get_sw3_IgnoreBool)
    call_instance = CMOCK_GUTS_NONE;
  UNITY_SET_DETAIL(CMockString_board_io__get_sw3);
  UNITY_TEST_ASSERT(CMOCK_GUTS_NONE == call_instance, cmock_line, CMockStringCalledLess);
  UNITY_CLR_DETAILS();
  if (Mock.board_io__get_sw3_CallbackFunctionPointer != NULL)
    call_instance = CMOCK_GUTS_NONE;
}

void Mockboard_io_Init(void)
{
  Mockboard_io_Destroy();
}

void Mockboard_io_Destroy(void)
{
  CMock_Guts_MemFreeAll();
  memset(&Mock, 0, sizeof(Mock));
}

void board_io__initialize(void)
{
  UNITY_LINE_TYPE cmock_line = TEST_LINE_NUM;
  CMOCK_board_io__initialize_CALL_INSTANCE* cmock_call_instance;
  UNITY_SET_DETAIL(CMockString_board_io__initialize);
  cmock_call_instance = (CMOCK_board_io__initialize_CALL_INSTANCE*)CMock_Guts_GetAddressFor(Mock.board_io__initialize_CallInstance);
  Mock.board_io__initialize_CallInstance = CMock_Guts_MemNext(Mock.board_io__initialize_CallInstance);
  if (Mock.board_io__initialize_IgnoreBool)
  {
    UNITY_CLR_DETAILS();
    return;
  }
  if (!Mock.board_io__initialize_CallbackBool &&
      Mock.board_io__initialize_CallbackFunctionPointer != NULL)
  {
    Mock.board_io__initialize_CallbackFunctionPointer(Mock.board_io__initialize_CallbackCalls++);
    UNITY_CLR_DETAILS();
    return;
  }
  UNITY_TEST_ASSERT_NOT_NULL(cmock_call_instance, cmock_line, CMockStringCalledMore);
  cmock_line = cmock_call_instance->LineNumber;
  if (Mock.board_io__initialize_CallbackFunctionPointer != NULL)
  {
    Mock.board_io__initialize_CallbackFunctionPointer(Mock.board_io__initialize_CallbackCalls++);
  }
  if (cmock_call_instance->ExceptionToThrow != CEXCEPTION_NONE)
  {
    UNITY_CLR_DETAILS();
    Throw(cmock_call_instance->ExceptionToThrow);
  }
  UNITY_CLR_DETAILS();
}

void board_io__initialize_CMockIgnore(void)
{
  Mock.board_io__initialize_IgnoreBool = (int)1;
}

void board_io__initialize_CMockExpect(UNITY_LINE_TYPE cmock_line)
{
  CMOCK_MEM_INDEX_TYPE cmock_guts_index = CMock_Guts_MemNew(sizeof(CMOCK_board_io__initialize_CALL_INSTANCE));
  CMOCK_board_io__initialize_CALL_INSTANCE* cmock_call_instance = (CMOCK_board_io__initialize_CALL_INSTANCE*)CMock_Guts_GetAddressFor(cmock_guts_index);
  UNITY_TEST_ASSERT_NOT_NULL(cmock_call_instance, cmock_line, CMockStringOutOfMemory);
  memset(cmock_call_instance, 0, sizeof(*cmock_call_instance));
  Mock.board_io__initialize_CallInstance = CMock_Guts_MemChain(Mock.board_io__initialize_CallInstance, cmock_guts_index);
  Mock.board_io__initialize_IgnoreBool = (int)0;
  cmock_call_instance->LineNumber = cmock_line;
  cmock_call_instance->ExceptionToThrow = CEXCEPTION_NONE;
  cmock_call_instance->ExpectAnyArgsBool = (int)0;
}

void board_io__initialize_AddCallback(CMOCK_board_io__initialize_CALLBACK Callback)
{
  Mock.board_io__initialize_IgnoreBool = (int)0;
  Mock.board_io__initialize_CallbackBool = (int)1;
  Mock.board_io__initialize_CallbackFunctionPointer = Callback;
}

void board_io__initialize_Stub(CMOCK_board_io__initialize_CALLBACK Callback)
{
  Mock.board_io__initialize_IgnoreBool = (int)0;
  Mock.board_io__initialize_CallbackBool = (int)0;
  Mock.board_io__initialize_CallbackFunctionPointer = Callback;
}

void board_io__initialize_CMockExpectAndThrow(UNITY_LINE_TYPE cmock_line, CEXCEPTION_T cmock_to_throw)
{
  CMOCK_MEM_INDEX_TYPE cmock_guts_index = CMock_Guts_MemNew(sizeof(CMOCK_board_io__initialize_CALL_INSTANCE));
  CMOCK_board_io__initialize_CALL_INSTANCE* cmock_call_instance = (CMOCK_board_io__initialize_CALL_INSTANCE*)CMock_Guts_GetAddressFor(cmock_guts_index);
  UNITY_TEST_ASSERT_NOT_NULL(cmock_call_instance, cmock_line, CMockStringOutOfMemory);
  memset(cmock_call_instance, 0, sizeof(*cmock_call_instance));
  Mock.board_io__initialize_CallInstance = CMock_Guts_MemChain(Mock.board_io__initialize_CallInstance, cmock_guts_index);
  Mock.board_io__initialize_IgnoreBool = (int)0;
  cmock_call_instance->LineNumber = cmock_line;
  cmock_call_instance->ExceptionToThrow = CEXCEPTION_NONE;
  cmock_call_instance->ExpectAnyArgsBool = (int)0;
  cmock_call_instance->ExceptionToThrow = cmock_to_throw;
}

void board_io__sd_card_cs(void)
{
  UNITY_LINE_TYPE cmock_line = TEST_LINE_NUM;
  CMOCK_board_io__sd_card_cs_CALL_INSTANCE* cmock_call_instance;
  UNITY_SET_DETAIL(CMockString_board_io__sd_card_cs);
  cmock_call_instance = (CMOCK_board_io__sd_card_cs_CALL_INSTANCE*)CMock_Guts_GetAddressFor(Mock.board_io__sd_card_cs_CallInstance);
  Mock.board_io__sd_card_cs_CallInstance = CMock_Guts_MemNext(Mock.board_io__sd_card_cs_CallInstance);
  if (Mock.board_io__sd_card_cs_IgnoreBool)
  {
    UNITY_CLR_DETAILS();
    return;
  }
  if (!Mock.board_io__sd_card_cs_CallbackBool &&
      Mock.board_io__sd_card_cs_CallbackFunctionPointer != NULL)
  {
    Mock.board_io__sd_card_cs_CallbackFunctionPointer(Mock.board_io__sd_card_cs_CallbackCalls++);
    UNITY_CLR_DETAILS();
    return;
  }
  UNITY_TEST_ASSERT_NOT_NULL(cmock_call_instance, cmock_line, CMockStringCalledMore);
  cmock_line = cmock_call_instance->LineNumber;
  if (Mock.board_io__sd_card_cs_CallbackFunctionPointer != NULL)
  {
    Mock.board_io__sd_card_cs_CallbackFunctionPointer(Mock.board_io__sd_card_cs_CallbackCalls++);
  }
  if (cmock_call_instance->ExceptionToThrow != CEXCEPTION_NONE)
  {
    UNITY_CLR_DETAILS();
    Throw(cmock_call_instance->ExceptionToThrow);
  }
  UNITY_CLR_DETAILS();
}

void board_io__sd_card_cs_CMockIgnore(void)
{
  Mock.board_io__sd_card_cs_IgnoreBool = (int)1;
}

void board_io__sd_card_cs_CMockExpect(UNITY_LINE_TYPE cmock_line)
{
  CMOCK_MEM_INDEX_TYPE cmock_guts_index = CMock_Guts_MemNew(sizeof(CMOCK_board_io__sd_card_cs_CALL_INSTANCE));
  CMOCK_board_io__sd_card_cs_CALL_INSTANCE* cmock_call_instance = (CMOCK_board_io__sd_card_cs_CALL_INSTANCE*)CMock_Guts_GetAddressFor(cmock_guts_index);
  UNITY_TEST_ASSERT_NOT_NULL(cmock_call_instance, cmock_line, CMockStringOutOfMemory);
  memset(cmock_call_instance, 0, sizeof(*cmock_call_instance));
  Mock.board_io__sd_card_cs_CallInstance = CMock_Guts_MemChain(Mock.board_io__sd_card_cs_CallInstance, cmock_guts_index);
  Mock.board_io__sd_card_cs_IgnoreBool = (int)0;
  cmock_call_instance->LineNumber = cmock_line;
  cmock_call_instance->ExceptionToThrow = CEXCEPTION_NONE;
  cmock_call_instance->ExpectAnyArgsBool = (int)0;
}

void board_io__sd_card_cs_AddCallback(CMOCK_board_io__sd_card_cs_CALLBACK Callback)
{
  Mock.board_io__sd_card_cs_IgnoreBool = (int)0;
  Mock.board_io__sd_card_cs_CallbackBool = (int)1;
  Mock.board_io__sd_card_cs_CallbackFunctionPointer = Callback;
}

void board_io__sd_card_cs_Stub(CMOCK_board_io__sd_card_cs_CALLBACK Callback)
{
  Mock.board_io__sd_card_cs_IgnoreBool = (int)0;
  Mock.board_io__sd_card_cs_CallbackBool = (int)0;
  Mock.board_io__sd_card_cs_CallbackFunctionPointer = Callback;
}

void board_io__sd_card_cs_CMockExpectAndThrow(UNITY_LINE_TYPE cmock_line, CEXCEPTION_T cmock_to_throw)
{
  CMOCK_MEM_INDEX_TYPE cmock_guts_index = CMock_Guts_MemNew(sizeof(CMOCK_board_io__sd_card_cs_CALL_INSTANCE));
  CMOCK_board_io__sd_card_cs_CALL_INSTANCE* cmock_call_instance = (CMOCK_board_io__sd_card_cs_CALL_INSTANCE*)CMock_Guts_GetAddressFor(cmock_guts_index);
  UNITY_TEST_ASSERT_NOT_NULL(cmock_call_instance, cmock_line, CMockStringOutOfMemory);
  memset(cmock_call_instance, 0, sizeof(*cmock_call_instance));
  Mock.board_io__sd_card_cs_CallInstance = CMock_Guts_MemChain(Mock.board_io__sd_card_cs_CallInstance, cmock_guts_index);
  Mock.board_io__sd_card_cs_IgnoreBool = (int)0;
  cmock_call_instance->LineNumber = cmock_line;
  cmock_call_instance->ExceptionToThrow = CEXCEPTION_NONE;
  cmock_call_instance->ExpectAnyArgsBool = (int)0;
  cmock_call_instance->ExceptionToThrow = cmock_to_throw;
}

void board_io__sd_card_ds(void)
{
  UNITY_LINE_TYPE cmock_line = TEST_LINE_NUM;
  CMOCK_board_io__sd_card_ds_CALL_INSTANCE* cmock_call_instance;
  UNITY_SET_DETAIL(CMockString_board_io__sd_card_ds);
  cmock_call_instance = (CMOCK_board_io__sd_card_ds_CALL_INSTANCE*)CMock_Guts_GetAddressFor(Mock.board_io__sd_card_ds_CallInstance);
  Mock.board_io__sd_card_ds_CallInstance = CMock_Guts_MemNext(Mock.board_io__sd_card_ds_CallInstance);
  if (Mock.board_io__sd_card_ds_IgnoreBool)
  {
    UNITY_CLR_DETAILS();
    return;
  }
  if (!Mock.board_io__sd_card_ds_CallbackBool &&
      Mock.board_io__sd_card_ds_CallbackFunctionPointer != NULL)
  {
    Mock.board_io__sd_card_ds_CallbackFunctionPointer(Mock.board_io__sd_card_ds_CallbackCalls++);
    UNITY_CLR_DETAILS();
    return;
  }
  UNITY_TEST_ASSERT_NOT_NULL(cmock_call_instance, cmock_line, CMockStringCalledMore);
  cmock_line = cmock_call_instance->LineNumber;
  if (Mock.board_io__sd_card_ds_CallbackFunctionPointer != NULL)
  {
    Mock.board_io__sd_card_ds_CallbackFunctionPointer(Mock.board_io__sd_card_ds_CallbackCalls++);
  }
  if (cmock_call_instance->ExceptionToThrow != CEXCEPTION_NONE)
  {
    UNITY_CLR_DETAILS();
    Throw(cmock_call_instance->ExceptionToThrow);
  }
  UNITY_CLR_DETAILS();
}

void board_io__sd_card_ds_CMockIgnore(void)
{
  Mock.board_io__sd_card_ds_IgnoreBool = (int)1;
}

void board_io__sd_card_ds_CMockExpect(UNITY_LINE_TYPE cmock_line)
{
  CMOCK_MEM_INDEX_TYPE cmock_guts_index = CMock_Guts_MemNew(sizeof(CMOCK_board_io__sd_card_ds_CALL_INSTANCE));
  CMOCK_board_io__sd_card_ds_CALL_INSTANCE* cmock_call_instance = (CMOCK_board_io__sd_card_ds_CALL_INSTANCE*)CMock_Guts_GetAddressFor(cmock_guts_index);
  UNITY_TEST_ASSERT_NOT_NULL(cmock_call_instance, cmock_line, CMockStringOutOfMemory);
  memset(cmock_call_instance, 0, sizeof(*cmock_call_instance));
  Mock.board_io__sd_card_ds_CallInstance = CMock_Guts_MemChain(Mock.board_io__sd_card_ds_CallInstance, cmock_guts_index);
  Mock.board_io__sd_card_ds_IgnoreBool = (int)0;
  cmock_call_instance->LineNumber = cmock_line;
  cmock_call_instance->ExceptionToThrow = CEXCEPTION_NONE;
  cmock_call_instance->ExpectAnyArgsBool = (int)0;
}

void board_io__sd_card_ds_AddCallback(CMOCK_board_io__sd_card_ds_CALLBACK Callback)
{
  Mock.board_io__sd_card_ds_IgnoreBool = (int)0;
  Mock.board_io__sd_card_ds_CallbackBool = (int)1;
  Mock.board_io__sd_card_ds_CallbackFunctionPointer = Callback;
}

void board_io__sd_card_ds_Stub(CMOCK_board_io__sd_card_ds_CALLBACK Callback)
{
  Mock.board_io__sd_card_ds_IgnoreBool = (int)0;
  Mock.board_io__sd_card_ds_CallbackBool = (int)0;
  Mock.board_io__sd_card_ds_CallbackFunctionPointer = Callback;
}

void board_io__sd_card_ds_CMockExpectAndThrow(UNITY_LINE_TYPE cmock_line, CEXCEPTION_T cmock_to_throw)
{
  CMOCK_MEM_INDEX_TYPE cmock_guts_index = CMock_Guts_MemNew(sizeof(CMOCK_board_io__sd_card_ds_CALL_INSTANCE));
  CMOCK_board_io__sd_card_ds_CALL_INSTANCE* cmock_call_instance = (CMOCK_board_io__sd_card_ds_CALL_INSTANCE*)CMock_Guts_GetAddressFor(cmock_guts_index);
  UNITY_TEST_ASSERT_NOT_NULL(cmock_call_instance, cmock_line, CMockStringOutOfMemory);
  memset(cmock_call_instance, 0, sizeof(*cmock_call_instance));
  Mock.board_io__sd_card_ds_CallInstance = CMock_Guts_MemChain(Mock.board_io__sd_card_ds_CallInstance, cmock_guts_index);
  Mock.board_io__sd_card_ds_IgnoreBool = (int)0;
  cmock_call_instance->LineNumber = cmock_line;
  cmock_call_instance->ExceptionToThrow = CEXCEPTION_NONE;
  cmock_call_instance->ExpectAnyArgsBool = (int)0;
  cmock_call_instance->ExceptionToThrow = cmock_to_throw;
}

bool board_io__sd_card_is_present(void)
{
  UNITY_LINE_TYPE cmock_line = TEST_LINE_NUM;
  CMOCK_board_io__sd_card_is_present_CALL_INSTANCE* cmock_call_instance;
  UNITY_SET_DETAIL(CMockString_board_io__sd_card_is_present);
  cmock_call_instance = (CMOCK_board_io__sd_card_is_present_CALL_INSTANCE*)CMock_Guts_GetAddressFor(Mock.board_io__sd_card_is_present_CallInstance);
  Mock.board_io__sd_card_is_present_CallInstance = CMock_Guts_MemNext(Mock.board_io__sd_card_is_present_CallInstance);
  if (Mock.board_io__sd_card_is_present_IgnoreBool)
  {
    UNITY_CLR_DETAILS();
    if (cmock_call_instance == NULL)
      return Mock.board_io__sd_card_is_present_FinalReturn;
    Mock.board_io__sd_card_is_present_FinalReturn = cmock_call_instance->ReturnVal;
    return cmock_call_instance->ReturnVal;
  }
  if (!Mock.board_io__sd_card_is_present_CallbackBool &&
      Mock.board_io__sd_card_is_present_CallbackFunctionPointer != NULL)
  {
    bool ret = Mock.board_io__sd_card_is_present_CallbackFunctionPointer(Mock.board_io__sd_card_is_present_CallbackCalls++);
    UNITY_CLR_DETAILS();
    return ret;
  }
  UNITY_TEST_ASSERT_NOT_NULL(cmock_call_instance, cmock_line, CMockStringCalledMore);
  cmock_line = cmock_call_instance->LineNumber;
  if (Mock.board_io__sd_card_is_present_CallbackFunctionPointer != NULL)
  {
    cmock_call_instance->ReturnVal = Mock.board_io__sd_card_is_present_CallbackFunctionPointer(Mock.board_io__sd_card_is_present_CallbackCalls++);
  }
  if (cmock_call_instance->ExceptionToThrow != CEXCEPTION_NONE)
  {
    UNITY_CLR_DETAILS();
    Throw(cmock_call_instance->ExceptionToThrow);
  }
  UNITY_CLR_DETAILS();
  return cmock_call_instance->ReturnVal;
}

void board_io__sd_card_is_present_CMockIgnoreAndReturn(UNITY_LINE_TYPE cmock_line, bool cmock_to_return)
{
  CMOCK_MEM_INDEX_TYPE cmock_guts_index = CMock_Guts_MemNew(sizeof(CMOCK_board_io__sd_card_is_present_CALL_INSTANCE));
  CMOCK_board_io__sd_card_is_present_CALL_INSTANCE* cmock_call_instance = (CMOCK_board_io__sd_card_is_present_CALL_INSTANCE*)CMock_Guts_GetAddressFor(cmock_guts_index);
  UNITY_TEST_ASSERT_NOT_NULL(cmock_call_instance, cmock_line, CMockStringOutOfMemory);
  memset(cmock_call_instance, 0, sizeof(*cmock_call_instance));
  Mock.board_io__sd_card_is_present_CallInstance = CMock_Guts_MemChain(Mock.board_io__sd_card_is_present_CallInstance, cmock_guts_index);
  Mock.board_io__sd_card_is_present_IgnoreBool = (int)0;
  cmock_call_instance->LineNumber = cmock_line;
  cmock_call_instance->ExceptionToThrow = CEXCEPTION_NONE;
  cmock_call_instance->ExpectAnyArgsBool = (int)0;
  cmock_call_instance->ReturnVal = cmock_to_return;
  Mock.board_io__sd_card_is_present_IgnoreBool = (int)1;
}

void board_io__sd_card_is_present_CMockExpectAndReturn(UNITY_LINE_TYPE cmock_line, bool cmock_to_return)
{
  CMOCK_MEM_INDEX_TYPE cmock_guts_index = CMock_Guts_MemNew(sizeof(CMOCK_board_io__sd_card_is_present_CALL_INSTANCE));
  CMOCK_board_io__sd_card_is_present_CALL_INSTANCE* cmock_call_instance = (CMOCK_board_io__sd_card_is_present_CALL_INSTANCE*)CMock_Guts_GetAddressFor(cmock_guts_index);
  UNITY_TEST_ASSERT_NOT_NULL(cmock_call_instance, cmock_line, CMockStringOutOfMemory);
  memset(cmock_call_instance, 0, sizeof(*cmock_call_instance));
  Mock.board_io__sd_card_is_present_CallInstance = CMock_Guts_MemChain(Mock.board_io__sd_card_is_present_CallInstance, cmock_guts_index);
  Mock.board_io__sd_card_is_present_IgnoreBool = (int)0;
  cmock_call_instance->LineNumber = cmock_line;
  cmock_call_instance->ExceptionToThrow = CEXCEPTION_NONE;
  cmock_call_instance->ExpectAnyArgsBool = (int)0;
  cmock_call_instance->ReturnVal = cmock_to_return;
}

void board_io__sd_card_is_present_AddCallback(CMOCK_board_io__sd_card_is_present_CALLBACK Callback)
{
  Mock.board_io__sd_card_is_present_IgnoreBool = (int)0;
  Mock.board_io__sd_card_is_present_CallbackBool = (int)1;
  Mock.board_io__sd_card_is_present_CallbackFunctionPointer = Callback;
}

void board_io__sd_card_is_present_Stub(CMOCK_board_io__sd_card_is_present_CALLBACK Callback)
{
  Mock.board_io__sd_card_is_present_IgnoreBool = (int)0;
  Mock.board_io__sd_card_is_present_CallbackBool = (int)0;
  Mock.board_io__sd_card_is_present_CallbackFunctionPointer = Callback;
}

void board_io__sd_card_is_present_CMockExpectAndThrow(UNITY_LINE_TYPE cmock_line, CEXCEPTION_T cmock_to_throw)
{
  CMOCK_MEM_INDEX_TYPE cmock_guts_index = CMock_Guts_MemNew(sizeof(CMOCK_board_io__sd_card_is_present_CALL_INSTANCE));
  CMOCK_board_io__sd_card_is_present_CALL_INSTANCE* cmock_call_instance = (CMOCK_board_io__sd_card_is_present_CALL_INSTANCE*)CMock_Guts_GetAddressFor(cmock_guts_index);
  UNITY_TEST_ASSERT_NOT_NULL(cmock_call_instance, cmock_line, CMockStringOutOfMemory);
  memset(cmock_call_instance, 0, sizeof(*cmock_call_instance));
  Mock.board_io__sd_card_is_present_CallInstance = CMock_Guts_MemChain(Mock.board_io__sd_card_is_present_CallInstance, cmock_guts_index);
  Mock.board_io__sd_card_is_present_IgnoreBool = (int)0;
  cmock_call_instance->LineNumber = cmock_line;
  cmock_call_instance->ExceptionToThrow = CEXCEPTION_NONE;
  cmock_call_instance->ExpectAnyArgsBool = (int)0;
  cmock_call_instance->ExceptionToThrow = cmock_to_throw;
}

gpio_s board_io__get_led0(void)
{
  UNITY_LINE_TYPE cmock_line = TEST_LINE_NUM;
  CMOCK_board_io__get_led0_CALL_INSTANCE* cmock_call_instance;
  UNITY_SET_DETAIL(CMockString_board_io__get_led0);
  cmock_call_instance = (CMOCK_board_io__get_led0_CALL_INSTANCE*)CMock_Guts_GetAddressFor(Mock.board_io__get_led0_CallInstance);
  Mock.board_io__get_led0_CallInstance = CMock_Guts_MemNext(Mock.board_io__get_led0_CallInstance);
  if (Mock.board_io__get_led0_IgnoreBool)
  {
    UNITY_CLR_DETAILS();
    if (cmock_call_instance == NULL)
      return Mock.board_io__get_led0_FinalReturn;
    memcpy((void*)(&Mock.board_io__get_led0_FinalReturn), (void*)(&cmock_call_instance->ReturnVal),
         sizeof(gpio_s[sizeof(cmock_call_instance->ReturnVal) == sizeof(gpio_s) ? 1 : -1])); /* add gpio_s to :treat_as_array if this causes an error */
    return cmock_call_instance->ReturnVal;
  }
  if (!Mock.board_io__get_led0_CallbackBool &&
      Mock.board_io__get_led0_CallbackFunctionPointer != NULL)
  {
    gpio_s ret = Mock.board_io__get_led0_CallbackFunctionPointer(Mock.board_io__get_led0_CallbackCalls++);
    UNITY_CLR_DETAILS();
    return ret;
  }
  UNITY_TEST_ASSERT_NOT_NULL(cmock_call_instance, cmock_line, CMockStringCalledMore);
  cmock_line = cmock_call_instance->LineNumber;
  if (Mock.board_io__get_led0_CallbackFunctionPointer != NULL)
  {
    cmock_call_instance->ReturnVal = Mock.board_io__get_led0_CallbackFunctionPointer(Mock.board_io__get_led0_CallbackCalls++);
  }
  if (cmock_call_instance->ExceptionToThrow != CEXCEPTION_NONE)
  {
    UNITY_CLR_DETAILS();
    Throw(cmock_call_instance->ExceptionToThrow);
  }
  UNITY_CLR_DETAILS();
  return cmock_call_instance->ReturnVal;
}

void board_io__get_led0_CMockIgnoreAndReturn(UNITY_LINE_TYPE cmock_line, gpio_s cmock_to_return)
{
  CMOCK_MEM_INDEX_TYPE cmock_guts_index = CMock_Guts_MemNew(sizeof(CMOCK_board_io__get_led0_CALL_INSTANCE));
  CMOCK_board_io__get_led0_CALL_INSTANCE* cmock_call_instance = (CMOCK_board_io__get_led0_CALL_INSTANCE*)CMock_Guts_GetAddressFor(cmock_guts_index);
  UNITY_TEST_ASSERT_NOT_NULL(cmock_call_instance, cmock_line, CMockStringOutOfMemory);
  memset(cmock_call_instance, 0, sizeof(*cmock_call_instance));
  Mock.board_io__get_led0_CallInstance = CMock_Guts_MemChain(Mock.board_io__get_led0_CallInstance, cmock_guts_index);
  Mock.board_io__get_led0_IgnoreBool = (int)0;
  cmock_call_instance->LineNumber = cmock_line;
  cmock_call_instance->ExceptionToThrow = CEXCEPTION_NONE;
  cmock_call_instance->ExpectAnyArgsBool = (int)0;
  cmock_call_instance->ReturnVal = cmock_to_return;
  Mock.board_io__get_led0_IgnoreBool = (int)1;
}

void board_io__get_led0_CMockExpectAndReturn(UNITY_LINE_TYPE cmock_line, gpio_s cmock_to_return)
{
  CMOCK_MEM_INDEX_TYPE cmock_guts_index = CMock_Guts_MemNew(sizeof(CMOCK_board_io__get_led0_CALL_INSTANCE));
  CMOCK_board_io__get_led0_CALL_INSTANCE* cmock_call_instance = (CMOCK_board_io__get_led0_CALL_INSTANCE*)CMock_Guts_GetAddressFor(cmock_guts_index);
  UNITY_TEST_ASSERT_NOT_NULL(cmock_call_instance, cmock_line, CMockStringOutOfMemory);
  memset(cmock_call_instance, 0, sizeof(*cmock_call_instance));
  Mock.board_io__get_led0_CallInstance = CMock_Guts_MemChain(Mock.board_io__get_led0_CallInstance, cmock_guts_index);
  Mock.board_io__get_led0_IgnoreBool = (int)0;
  cmock_call_instance->LineNumber = cmock_line;
  cmock_call_instance->ExceptionToThrow = CEXCEPTION_NONE;
  cmock_call_instance->ExpectAnyArgsBool = (int)0;
  memcpy((void*)(&cmock_call_instance->ReturnVal), (void*)(&cmock_to_return),
         sizeof(gpio_s[sizeof(cmock_to_return) == sizeof(gpio_s) ? 1 : -1])); /* add gpio_s to :treat_as_array if this causes an error */
}

void board_io__get_led0_AddCallback(CMOCK_board_io__get_led0_CALLBACK Callback)
{
  Mock.board_io__get_led0_IgnoreBool = (int)0;
  Mock.board_io__get_led0_CallbackBool = (int)1;
  Mock.board_io__get_led0_CallbackFunctionPointer = Callback;
}

void board_io__get_led0_Stub(CMOCK_board_io__get_led0_CALLBACK Callback)
{
  Mock.board_io__get_led0_IgnoreBool = (int)0;
  Mock.board_io__get_led0_CallbackBool = (int)0;
  Mock.board_io__get_led0_CallbackFunctionPointer = Callback;
}

void board_io__get_led0_CMockExpectAndThrow(UNITY_LINE_TYPE cmock_line, CEXCEPTION_T cmock_to_throw)
{
  CMOCK_MEM_INDEX_TYPE cmock_guts_index = CMock_Guts_MemNew(sizeof(CMOCK_board_io__get_led0_CALL_INSTANCE));
  CMOCK_board_io__get_led0_CALL_INSTANCE* cmock_call_instance = (CMOCK_board_io__get_led0_CALL_INSTANCE*)CMock_Guts_GetAddressFor(cmock_guts_index);
  UNITY_TEST_ASSERT_NOT_NULL(cmock_call_instance, cmock_line, CMockStringOutOfMemory);
  memset(cmock_call_instance, 0, sizeof(*cmock_call_instance));
  Mock.board_io__get_led0_CallInstance = CMock_Guts_MemChain(Mock.board_io__get_led0_CallInstance, cmock_guts_index);
  Mock.board_io__get_led0_IgnoreBool = (int)0;
  cmock_call_instance->LineNumber = cmock_line;
  cmock_call_instance->ExceptionToThrow = CEXCEPTION_NONE;
  cmock_call_instance->ExpectAnyArgsBool = (int)0;
  cmock_call_instance->ExceptionToThrow = cmock_to_throw;
}

gpio_s board_io__get_led1(void)
{
  UNITY_LINE_TYPE cmock_line = TEST_LINE_NUM;
  CMOCK_board_io__get_led1_CALL_INSTANCE* cmock_call_instance;
  UNITY_SET_DETAIL(CMockString_board_io__get_led1);
  cmock_call_instance = (CMOCK_board_io__get_led1_CALL_INSTANCE*)CMock_Guts_GetAddressFor(Mock.board_io__get_led1_CallInstance);
  Mock.board_io__get_led1_CallInstance = CMock_Guts_MemNext(Mock.board_io__get_led1_CallInstance);
  if (Mock.board_io__get_led1_IgnoreBool)
  {
    UNITY_CLR_DETAILS();
    if (cmock_call_instance == NULL)
      return Mock.board_io__get_led1_FinalReturn;
    memcpy((void*)(&Mock.board_io__get_led1_FinalReturn), (void*)(&cmock_call_instance->ReturnVal),
         sizeof(gpio_s[sizeof(cmock_call_instance->ReturnVal) == sizeof(gpio_s) ? 1 : -1])); /* add gpio_s to :treat_as_array if this causes an error */
    return cmock_call_instance->ReturnVal;
  }
  if (!Mock.board_io__get_led1_CallbackBool &&
      Mock.board_io__get_led1_CallbackFunctionPointer != NULL)
  {
    gpio_s ret = Mock.board_io__get_led1_CallbackFunctionPointer(Mock.board_io__get_led1_CallbackCalls++);
    UNITY_CLR_DETAILS();
    return ret;
  }
  UNITY_TEST_ASSERT_NOT_NULL(cmock_call_instance, cmock_line, CMockStringCalledMore);
  cmock_line = cmock_call_instance->LineNumber;
  if (Mock.board_io__get_led1_CallbackFunctionPointer != NULL)
  {
    cmock_call_instance->ReturnVal = Mock.board_io__get_led1_CallbackFunctionPointer(Mock.board_io__get_led1_CallbackCalls++);
  }
  if (cmock_call_instance->ExceptionToThrow != CEXCEPTION_NONE)
  {
    UNITY_CLR_DETAILS();
    Throw(cmock_call_instance->ExceptionToThrow);
  }
  UNITY_CLR_DETAILS();
  return cmock_call_instance->ReturnVal;
}

void board_io__get_led1_CMockIgnoreAndReturn(UNITY_LINE_TYPE cmock_line, gpio_s cmock_to_return)
{
  CMOCK_MEM_INDEX_TYPE cmock_guts_index = CMock_Guts_MemNew(sizeof(CMOCK_board_io__get_led1_CALL_INSTANCE));
  CMOCK_board_io__get_led1_CALL_INSTANCE* cmock_call_instance = (CMOCK_board_io__get_led1_CALL_INSTANCE*)CMock_Guts_GetAddressFor(cmock_guts_index);
  UNITY_TEST_ASSERT_NOT_NULL(cmock_call_instance, cmock_line, CMockStringOutOfMemory);
  memset(cmock_call_instance, 0, sizeof(*cmock_call_instance));
  Mock.board_io__get_led1_CallInstance = CMock_Guts_MemChain(Mock.board_io__get_led1_CallInstance, cmock_guts_index);
  Mock.board_io__get_led1_IgnoreBool = (int)0;
  cmock_call_instance->LineNumber = cmock_line;
  cmock_call_instance->ExceptionToThrow = CEXCEPTION_NONE;
  cmock_call_instance->ExpectAnyArgsBool = (int)0;
  cmock_call_instance->ReturnVal = cmock_to_return;
  Mock.board_io__get_led1_IgnoreBool = (int)1;
}

void board_io__get_led1_CMockExpectAndReturn(UNITY_LINE_TYPE cmock_line, gpio_s cmock_to_return)
{
  CMOCK_MEM_INDEX_TYPE cmock_guts_index = CMock_Guts_MemNew(sizeof(CMOCK_board_io__get_led1_CALL_INSTANCE));
  CMOCK_board_io__get_led1_CALL_INSTANCE* cmock_call_instance = (CMOCK_board_io__get_led1_CALL_INSTANCE*)CMock_Guts_GetAddressFor(cmock_guts_index);
  UNITY_TEST_ASSERT_NOT_NULL(cmock_call_instance, cmock_line, CMockStringOutOfMemory);
  memset(cmock_call_instance, 0, sizeof(*cmock_call_instance));
  Mock.board_io__get_led1_CallInstance = CMock_Guts_MemChain(Mock.board_io__get_led1_CallInstance, cmock_guts_index);
  Mock.board_io__get_led1_IgnoreBool = (int)0;
  cmock_call_instance->LineNumber = cmock_line;
  cmock_call_instance->ExceptionToThrow = CEXCEPTION_NONE;
  cmock_call_instance->ExpectAnyArgsBool = (int)0;
  memcpy((void*)(&cmock_call_instance->ReturnVal), (void*)(&cmock_to_return),
         sizeof(gpio_s[sizeof(cmock_to_return) == sizeof(gpio_s) ? 1 : -1])); /* add gpio_s to :treat_as_array if this causes an error */
}

void board_io__get_led1_AddCallback(CMOCK_board_io__get_led1_CALLBACK Callback)
{
  Mock.board_io__get_led1_IgnoreBool = (int)0;
  Mock.board_io__get_led1_CallbackBool = (int)1;
  Mock.board_io__get_led1_CallbackFunctionPointer = Callback;
}

void board_io__get_led1_Stub(CMOCK_board_io__get_led1_CALLBACK Callback)
{
  Mock.board_io__get_led1_IgnoreBool = (int)0;
  Mock.board_io__get_led1_CallbackBool = (int)0;
  Mock.board_io__get_led1_CallbackFunctionPointer = Callback;
}

void board_io__get_led1_CMockExpectAndThrow(UNITY_LINE_TYPE cmock_line, CEXCEPTION_T cmock_to_throw)
{
  CMOCK_MEM_INDEX_TYPE cmock_guts_index = CMock_Guts_MemNew(sizeof(CMOCK_board_io__get_led1_CALL_INSTANCE));
  CMOCK_board_io__get_led1_CALL_INSTANCE* cmock_call_instance = (CMOCK_board_io__get_led1_CALL_INSTANCE*)CMock_Guts_GetAddressFor(cmock_guts_index);
  UNITY_TEST_ASSERT_NOT_NULL(cmock_call_instance, cmock_line, CMockStringOutOfMemory);
  memset(cmock_call_instance, 0, sizeof(*cmock_call_instance));
  Mock.board_io__get_led1_CallInstance = CMock_Guts_MemChain(Mock.board_io__get_led1_CallInstance, cmock_guts_index);
  Mock.board_io__get_led1_IgnoreBool = (int)0;
  cmock_call_instance->LineNumber = cmock_line;
  cmock_call_instance->ExceptionToThrow = CEXCEPTION_NONE;
  cmock_call_instance->ExpectAnyArgsBool = (int)0;
  cmock_call_instance->ExceptionToThrow = cmock_to_throw;
}

gpio_s board_io__get_led2(void)
{
  UNITY_LINE_TYPE cmock_line = TEST_LINE_NUM;
  CMOCK_board_io__get_led2_CALL_INSTANCE* cmock_call_instance;
  UNITY_SET_DETAIL(CMockString_board_io__get_led2);
  cmock_call_instance = (CMOCK_board_io__get_led2_CALL_INSTANCE*)CMock_Guts_GetAddressFor(Mock.board_io__get_led2_CallInstance);
  Mock.board_io__get_led2_CallInstance = CMock_Guts_MemNext(Mock.board_io__get_led2_CallInstance);
  if (Mock.board_io__get_led2_IgnoreBool)
  {
    UNITY_CLR_DETAILS();
    if (cmock_call_instance == NULL)
      return Mock.board_io__get_led2_FinalReturn;
    memcpy((void*)(&Mock.board_io__get_led2_FinalReturn), (void*)(&cmock_call_instance->ReturnVal),
         sizeof(gpio_s[sizeof(cmock_call_instance->ReturnVal) == sizeof(gpio_s) ? 1 : -1])); /* add gpio_s to :treat_as_array if this causes an error */
    return cmock_call_instance->ReturnVal;
  }
  if (!Mock.board_io__get_led2_CallbackBool &&
      Mock.board_io__get_led2_CallbackFunctionPointer != NULL)
  {
    gpio_s ret = Mock.board_io__get_led2_CallbackFunctionPointer(Mock.board_io__get_led2_CallbackCalls++);
    UNITY_CLR_DETAILS();
    return ret;
  }
  UNITY_TEST_ASSERT_NOT_NULL(cmock_call_instance, cmock_line, CMockStringCalledMore);
  cmock_line = cmock_call_instance->LineNumber;
  if (Mock.board_io__get_led2_CallbackFunctionPointer != NULL)
  {
    cmock_call_instance->ReturnVal = Mock.board_io__get_led2_CallbackFunctionPointer(Mock.board_io__get_led2_CallbackCalls++);
  }
  if (cmock_call_instance->ExceptionToThrow != CEXCEPTION_NONE)
  {
    UNITY_CLR_DETAILS();
    Throw(cmock_call_instance->ExceptionToThrow);
  }
  UNITY_CLR_DETAILS();
  return cmock_call_instance->ReturnVal;
}

void board_io__get_led2_CMockIgnoreAndReturn(UNITY_LINE_TYPE cmock_line, gpio_s cmock_to_return)
{
  CMOCK_MEM_INDEX_TYPE cmock_guts_index = CMock_Guts_MemNew(sizeof(CMOCK_board_io__get_led2_CALL_INSTANCE));
  CMOCK_board_io__get_led2_CALL_INSTANCE* cmock_call_instance = (CMOCK_board_io__get_led2_CALL_INSTANCE*)CMock_Guts_GetAddressFor(cmock_guts_index);
  UNITY_TEST_ASSERT_NOT_NULL(cmock_call_instance, cmock_line, CMockStringOutOfMemory);
  memset(cmock_call_instance, 0, sizeof(*cmock_call_instance));
  Mock.board_io__get_led2_CallInstance = CMock_Guts_MemChain(Mock.board_io__get_led2_CallInstance, cmock_guts_index);
  Mock.board_io__get_led2_IgnoreBool = (int)0;
  cmock_call_instance->LineNumber = cmock_line;
  cmock_call_instance->ExceptionToThrow = CEXCEPTION_NONE;
  cmock_call_instance->ExpectAnyArgsBool = (int)0;
  cmock_call_instance->ReturnVal = cmock_to_return;
  Mock.board_io__get_led2_IgnoreBool = (int)1;
}

void board_io__get_led2_CMockExpectAndReturn(UNITY_LINE_TYPE cmock_line, gpio_s cmock_to_return)
{
  CMOCK_MEM_INDEX_TYPE cmock_guts_index = CMock_Guts_MemNew(sizeof(CMOCK_board_io__get_led2_CALL_INSTANCE));
  CMOCK_board_io__get_led2_CALL_INSTANCE* cmock_call_instance = (CMOCK_board_io__get_led2_CALL_INSTANCE*)CMock_Guts_GetAddressFor(cmock_guts_index);
  UNITY_TEST_ASSERT_NOT_NULL(cmock_call_instance, cmock_line, CMockStringOutOfMemory);
  memset(cmock_call_instance, 0, sizeof(*cmock_call_instance));
  Mock.board_io__get_led2_CallInstance = CMock_Guts_MemChain(Mock.board_io__get_led2_CallInstance, cmock_guts_index);
  Mock.board_io__get_led2_IgnoreBool = (int)0;
  cmock_call_instance->LineNumber = cmock_line;
  cmock_call_instance->ExceptionToThrow = CEXCEPTION_NONE;
  cmock_call_instance->ExpectAnyArgsBool = (int)0;
  memcpy((void*)(&cmock_call_instance->ReturnVal), (void*)(&cmock_to_return),
         sizeof(gpio_s[sizeof(cmock_to_return) == sizeof(gpio_s) ? 1 : -1])); /* add gpio_s to :treat_as_array if this causes an error */
}

void board_io__get_led2_AddCallback(CMOCK_board_io__get_led2_CALLBACK Callback)
{
  Mock.board_io__get_led2_IgnoreBool = (int)0;
  Mock.board_io__get_led2_CallbackBool = (int)1;
  Mock.board_io__get_led2_CallbackFunctionPointer = Callback;
}

void board_io__get_led2_Stub(CMOCK_board_io__get_led2_CALLBACK Callback)
{
  Mock.board_io__get_led2_IgnoreBool = (int)0;
  Mock.board_io__get_led2_CallbackBool = (int)0;
  Mock.board_io__get_led2_CallbackFunctionPointer = Callback;
}

void board_io__get_led2_CMockExpectAndThrow(UNITY_LINE_TYPE cmock_line, CEXCEPTION_T cmock_to_throw)
{
  CMOCK_MEM_INDEX_TYPE cmock_guts_index = CMock_Guts_MemNew(sizeof(CMOCK_board_io__get_led2_CALL_INSTANCE));
  CMOCK_board_io__get_led2_CALL_INSTANCE* cmock_call_instance = (CMOCK_board_io__get_led2_CALL_INSTANCE*)CMock_Guts_GetAddressFor(cmock_guts_index);
  UNITY_TEST_ASSERT_NOT_NULL(cmock_call_instance, cmock_line, CMockStringOutOfMemory);
  memset(cmock_call_instance, 0, sizeof(*cmock_call_instance));
  Mock.board_io__get_led2_CallInstance = CMock_Guts_MemChain(Mock.board_io__get_led2_CallInstance, cmock_guts_index);
  Mock.board_io__get_led2_IgnoreBool = (int)0;
  cmock_call_instance->LineNumber = cmock_line;
  cmock_call_instance->ExceptionToThrow = CEXCEPTION_NONE;
  cmock_call_instance->ExpectAnyArgsBool = (int)0;
  cmock_call_instance->ExceptionToThrow = cmock_to_throw;
}

gpio_s board_io__get_led3(void)
{
  UNITY_LINE_TYPE cmock_line = TEST_LINE_NUM;
  CMOCK_board_io__get_led3_CALL_INSTANCE* cmock_call_instance;
  UNITY_SET_DETAIL(CMockString_board_io__get_led3);
  cmock_call_instance = (CMOCK_board_io__get_led3_CALL_INSTANCE*)CMock_Guts_GetAddressFor(Mock.board_io__get_led3_CallInstance);
  Mock.board_io__get_led3_CallInstance = CMock_Guts_MemNext(Mock.board_io__get_led3_CallInstance);
  if (Mock.board_io__get_led3_IgnoreBool)
  {
    UNITY_CLR_DETAILS();
    if (cmock_call_instance == NULL)
      return Mock.board_io__get_led3_FinalReturn;
    memcpy((void*)(&Mock.board_io__get_led3_FinalReturn), (void*)(&cmock_call_instance->ReturnVal),
         sizeof(gpio_s[sizeof(cmock_call_instance->ReturnVal) == sizeof(gpio_s) ? 1 : -1])); /* add gpio_s to :treat_as_array if this causes an error */
    return cmock_call_instance->ReturnVal;
  }
  if (!Mock.board_io__get_led3_CallbackBool &&
      Mock.board_io__get_led3_CallbackFunctionPointer != NULL)
  {
    gpio_s ret = Mock.board_io__get_led3_CallbackFunctionPointer(Mock.board_io__get_led3_CallbackCalls++);
    UNITY_CLR_DETAILS();
    return ret;
  }
  UNITY_TEST_ASSERT_NOT_NULL(cmock_call_instance, cmock_line, CMockStringCalledMore);
  cmock_line = cmock_call_instance->LineNumber;
  if (Mock.board_io__get_led3_CallbackFunctionPointer != NULL)
  {
    cmock_call_instance->ReturnVal = Mock.board_io__get_led3_CallbackFunctionPointer(Mock.board_io__get_led3_CallbackCalls++);
  }
  if (cmock_call_instance->ExceptionToThrow != CEXCEPTION_NONE)
  {
    UNITY_CLR_DETAILS();
    Throw(cmock_call_instance->ExceptionToThrow);
  }
  UNITY_CLR_DETAILS();
  return cmock_call_instance->ReturnVal;
}

void board_io__get_led3_CMockIgnoreAndReturn(UNITY_LINE_TYPE cmock_line, gpio_s cmock_to_return)
{
  CMOCK_MEM_INDEX_TYPE cmock_guts_index = CMock_Guts_MemNew(sizeof(CMOCK_board_io__get_led3_CALL_INSTANCE));
  CMOCK_board_io__get_led3_CALL_INSTANCE* cmock_call_instance = (CMOCK_board_io__get_led3_CALL_INSTANCE*)CMock_Guts_GetAddressFor(cmock_guts_index);
  UNITY_TEST_ASSERT_NOT_NULL(cmock_call_instance, cmock_line, CMockStringOutOfMemory);
  memset(cmock_call_instance, 0, sizeof(*cmock_call_instance));
  Mock.board_io__get_led3_CallInstance = CMock_Guts_MemChain(Mock.board_io__get_led3_CallInstance, cmock_guts_index);
  Mock.board_io__get_led3_IgnoreBool = (int)0;
  cmock_call_instance->LineNumber = cmock_line;
  cmock_call_instance->ExceptionToThrow = CEXCEPTION_NONE;
  cmock_call_instance->ExpectAnyArgsBool = (int)0;
  cmock_call_instance->ReturnVal = cmock_to_return;
  Mock.board_io__get_led3_IgnoreBool = (int)1;
}

void board_io__get_led3_CMockExpectAndReturn(UNITY_LINE_TYPE cmock_line, gpio_s cmock_to_return)
{
  CMOCK_MEM_INDEX_TYPE cmock_guts_index = CMock_Guts_MemNew(sizeof(CMOCK_board_io__get_led3_CALL_INSTANCE));
  CMOCK_board_io__get_led3_CALL_INSTANCE* cmock_call_instance = (CMOCK_board_io__get_led3_CALL_INSTANCE*)CMock_Guts_GetAddressFor(cmock_guts_index);
  UNITY_TEST_ASSERT_NOT_NULL(cmock_call_instance, cmock_line, CMockStringOutOfMemory);
  memset(cmock_call_instance, 0, sizeof(*cmock_call_instance));
  Mock.board_io__get_led3_CallInstance = CMock_Guts_MemChain(Mock.board_io__get_led3_CallInstance, cmock_guts_index);
  Mock.board_io__get_led3_IgnoreBool = (int)0;
  cmock_call_instance->LineNumber = cmock_line;
  cmock_call_instance->ExceptionToThrow = CEXCEPTION_NONE;
  cmock_call_instance->ExpectAnyArgsBool = (int)0;
  memcpy((void*)(&cmock_call_instance->ReturnVal), (void*)(&cmock_to_return),
         sizeof(gpio_s[sizeof(cmock_to_return) == sizeof(gpio_s) ? 1 : -1])); /* add gpio_s to :treat_as_array if this causes an error */
}

void board_io__get_led3_AddCallback(CMOCK_board_io__get_led3_CALLBACK Callback)
{
  Mock.board_io__get_led3_IgnoreBool = (int)0;
  Mock.board_io__get_led3_CallbackBool = (int)1;
  Mock.board_io__get_led3_CallbackFunctionPointer = Callback;
}

void board_io__get_led3_Stub(CMOCK_board_io__get_led3_CALLBACK Callback)
{
  Mock.board_io__get_led3_IgnoreBool = (int)0;
  Mock.board_io__get_led3_CallbackBool = (int)0;
  Mock.board_io__get_led3_CallbackFunctionPointer = Callback;
}

void board_io__get_led3_CMockExpectAndThrow(UNITY_LINE_TYPE cmock_line, CEXCEPTION_T cmock_to_throw)
{
  CMOCK_MEM_INDEX_TYPE cmock_guts_index = CMock_Guts_MemNew(sizeof(CMOCK_board_io__get_led3_CALL_INSTANCE));
  CMOCK_board_io__get_led3_CALL_INSTANCE* cmock_call_instance = (CMOCK_board_io__get_led3_CALL_INSTANCE*)CMock_Guts_GetAddressFor(cmock_guts_index);
  UNITY_TEST_ASSERT_NOT_NULL(cmock_call_instance, cmock_line, CMockStringOutOfMemory);
  memset(cmock_call_instance, 0, sizeof(*cmock_call_instance));
  Mock.board_io__get_led3_CallInstance = CMock_Guts_MemChain(Mock.board_io__get_led3_CallInstance, cmock_guts_index);
  Mock.board_io__get_led3_IgnoreBool = (int)0;
  cmock_call_instance->LineNumber = cmock_line;
  cmock_call_instance->ExceptionToThrow = CEXCEPTION_NONE;
  cmock_call_instance->ExpectAnyArgsBool = (int)0;
  cmock_call_instance->ExceptionToThrow = cmock_to_throw;
}

gpio_s board_io__get_sw0(void)
{
  UNITY_LINE_TYPE cmock_line = TEST_LINE_NUM;
  CMOCK_board_io__get_sw0_CALL_INSTANCE* cmock_call_instance;
  UNITY_SET_DETAIL(CMockString_board_io__get_sw0);
  cmock_call_instance = (CMOCK_board_io__get_sw0_CALL_INSTANCE*)CMock_Guts_GetAddressFor(Mock.board_io__get_sw0_CallInstance);
  Mock.board_io__get_sw0_CallInstance = CMock_Guts_MemNext(Mock.board_io__get_sw0_CallInstance);
  if (Mock.board_io__get_sw0_IgnoreBool)
  {
    UNITY_CLR_DETAILS();
    if (cmock_call_instance == NULL)
      return Mock.board_io__get_sw0_FinalReturn;
    memcpy((void*)(&Mock.board_io__get_sw0_FinalReturn), (void*)(&cmock_call_instance->ReturnVal),
         sizeof(gpio_s[sizeof(cmock_call_instance->ReturnVal) == sizeof(gpio_s) ? 1 : -1])); /* add gpio_s to :treat_as_array if this causes an error */
    return cmock_call_instance->ReturnVal;
  }
  if (!Mock.board_io__get_sw0_CallbackBool &&
      Mock.board_io__get_sw0_CallbackFunctionPointer != NULL)
  {
    gpio_s ret = Mock.board_io__get_sw0_CallbackFunctionPointer(Mock.board_io__get_sw0_CallbackCalls++);
    UNITY_CLR_DETAILS();
    return ret;
  }
  UNITY_TEST_ASSERT_NOT_NULL(cmock_call_instance, cmock_line, CMockStringCalledMore);
  cmock_line = cmock_call_instance->LineNumber;
  if (Mock.board_io__get_sw0_CallbackFunctionPointer != NULL)
  {
    cmock_call_instance->ReturnVal = Mock.board_io__get_sw0_CallbackFunctionPointer(Mock.board_io__get_sw0_CallbackCalls++);
  }
  if (cmock_call_instance->ExceptionToThrow != CEXCEPTION_NONE)
  {
    UNITY_CLR_DETAILS();
    Throw(cmock_call_instance->ExceptionToThrow);
  }
  UNITY_CLR_DETAILS();
  return cmock_call_instance->ReturnVal;
}

void board_io__get_sw0_CMockIgnoreAndReturn(UNITY_LINE_TYPE cmock_line, gpio_s cmock_to_return)
{
  CMOCK_MEM_INDEX_TYPE cmock_guts_index = CMock_Guts_MemNew(sizeof(CMOCK_board_io__get_sw0_CALL_INSTANCE));
  CMOCK_board_io__get_sw0_CALL_INSTANCE* cmock_call_instance = (CMOCK_board_io__get_sw0_CALL_INSTANCE*)CMock_Guts_GetAddressFor(cmock_guts_index);
  UNITY_TEST_ASSERT_NOT_NULL(cmock_call_instance, cmock_line, CMockStringOutOfMemory);
  memset(cmock_call_instance, 0, sizeof(*cmock_call_instance));
  Mock.board_io__get_sw0_CallInstance = CMock_Guts_MemChain(Mock.board_io__get_sw0_CallInstance, cmock_guts_index);
  Mock.board_io__get_sw0_IgnoreBool = (int)0;
  cmock_call_instance->LineNumber = cmock_line;
  cmock_call_instance->ExceptionToThrow = CEXCEPTION_NONE;
  cmock_call_instance->ExpectAnyArgsBool = (int)0;
  cmock_call_instance->ReturnVal = cmock_to_return;
  Mock.board_io__get_sw0_IgnoreBool = (int)1;
}

void board_io__get_sw0_CMockExpectAndReturn(UNITY_LINE_TYPE cmock_line, gpio_s cmock_to_return)
{
  CMOCK_MEM_INDEX_TYPE cmock_guts_index = CMock_Guts_MemNew(sizeof(CMOCK_board_io__get_sw0_CALL_INSTANCE));
  CMOCK_board_io__get_sw0_CALL_INSTANCE* cmock_call_instance = (CMOCK_board_io__get_sw0_CALL_INSTANCE*)CMock_Guts_GetAddressFor(cmock_guts_index);
  UNITY_TEST_ASSERT_NOT_NULL(cmock_call_instance, cmock_line, CMockStringOutOfMemory);
  memset(cmock_call_instance, 0, sizeof(*cmock_call_instance));
  Mock.board_io__get_sw0_CallInstance = CMock_Guts_MemChain(Mock.board_io__get_sw0_CallInstance, cmock_guts_index);
  Mock.board_io__get_sw0_IgnoreBool = (int)0;
  cmock_call_instance->LineNumber = cmock_line;
  cmock_call_instance->ExceptionToThrow = CEXCEPTION_NONE;
  cmock_call_instance->ExpectAnyArgsBool = (int)0;
  memcpy((void*)(&cmock_call_instance->ReturnVal), (void*)(&cmock_to_return),
         sizeof(gpio_s[sizeof(cmock_to_return) == sizeof(gpio_s) ? 1 : -1])); /* add gpio_s to :treat_as_array if this causes an error */
}

void board_io__get_sw0_AddCallback(CMOCK_board_io__get_sw0_CALLBACK Callback)
{
  Mock.board_io__get_sw0_IgnoreBool = (int)0;
  Mock.board_io__get_sw0_CallbackBool = (int)1;
  Mock.board_io__get_sw0_CallbackFunctionPointer = Callback;
}

void board_io__get_sw0_Stub(CMOCK_board_io__get_sw0_CALLBACK Callback)
{
  Mock.board_io__get_sw0_IgnoreBool = (int)0;
  Mock.board_io__get_sw0_CallbackBool = (int)0;
  Mock.board_io__get_sw0_CallbackFunctionPointer = Callback;
}

void board_io__get_sw0_CMockExpectAndThrow(UNITY_LINE_TYPE cmock_line, CEXCEPTION_T cmock_to_throw)
{
  CMOCK_MEM_INDEX_TYPE cmock_guts_index = CMock_Guts_MemNew(sizeof(CMOCK_board_io__get_sw0_CALL_INSTANCE));
  CMOCK_board_io__get_sw0_CALL_INSTANCE* cmock_call_instance = (CMOCK_board_io__get_sw0_CALL_INSTANCE*)CMock_Guts_GetAddressFor(cmock_guts_index);
  UNITY_TEST_ASSERT_NOT_NULL(cmock_call_instance, cmock_line, CMockStringOutOfMemory);
  memset(cmock_call_instance, 0, sizeof(*cmock_call_instance));
  Mock.board_io__get_sw0_CallInstance = CMock_Guts_MemChain(Mock.board_io__get_sw0_CallInstance, cmock_guts_index);
  Mock.board_io__get_sw0_IgnoreBool = (int)0;
  cmock_call_instance->LineNumber = cmock_line;
  cmock_call_instance->ExceptionToThrow = CEXCEPTION_NONE;
  cmock_call_instance->ExpectAnyArgsBool = (int)0;
  cmock_call_instance->ExceptionToThrow = cmock_to_throw;
}

gpio_s board_io__get_sw1(void)
{
  UNITY_LINE_TYPE cmock_line = TEST_LINE_NUM;
  CMOCK_board_io__get_sw1_CALL_INSTANCE* cmock_call_instance;
  UNITY_SET_DETAIL(CMockString_board_io__get_sw1);
  cmock_call_instance = (CMOCK_board_io__get_sw1_CALL_INSTANCE*)CMock_Guts_GetAddressFor(Mock.board_io__get_sw1_CallInstance);
  Mock.board_io__get_sw1_CallInstance = CMock_Guts_MemNext(Mock.board_io__get_sw1_CallInstance);
  if (Mock.board_io__get_sw1_IgnoreBool)
  {
    UNITY_CLR_DETAILS();
    if (cmock_call_instance == NULL)
      return Mock.board_io__get_sw1_FinalReturn;
    memcpy((void*)(&Mock.board_io__get_sw1_FinalReturn), (void*)(&cmock_call_instance->ReturnVal),
         sizeof(gpio_s[sizeof(cmock_call_instance->ReturnVal) == sizeof(gpio_s) ? 1 : -1])); /* add gpio_s to :treat_as_array if this causes an error */
    return cmock_call_instance->ReturnVal;
  }
  if (!Mock.board_io__get_sw1_CallbackBool &&
      Mock.board_io__get_sw1_CallbackFunctionPointer != NULL)
  {
    gpio_s ret = Mock.board_io__get_sw1_CallbackFunctionPointer(Mock.board_io__get_sw1_CallbackCalls++);
    UNITY_CLR_DETAILS();
    return ret;
  }
  UNITY_TEST_ASSERT_NOT_NULL(cmock_call_instance, cmock_line, CMockStringCalledMore);
  cmock_line = cmock_call_instance->LineNumber;
  if (Mock.board_io__get_sw1_CallbackFunctionPointer != NULL)
  {
    cmock_call_instance->ReturnVal = Mock.board_io__get_sw1_CallbackFunctionPointer(Mock.board_io__get_sw1_CallbackCalls++);
  }
  if (cmock_call_instance->ExceptionToThrow != CEXCEPTION_NONE)
  {
    UNITY_CLR_DETAILS();
    Throw(cmock_call_instance->ExceptionToThrow);
  }
  UNITY_CLR_DETAILS();
  return cmock_call_instance->ReturnVal;
}

void board_io__get_sw1_CMockIgnoreAndReturn(UNITY_LINE_TYPE cmock_line, gpio_s cmock_to_return)
{
  CMOCK_MEM_INDEX_TYPE cmock_guts_index = CMock_Guts_MemNew(sizeof(CMOCK_board_io__get_sw1_CALL_INSTANCE));
  CMOCK_board_io__get_sw1_CALL_INSTANCE* cmock_call_instance = (CMOCK_board_io__get_sw1_CALL_INSTANCE*)CMock_Guts_GetAddressFor(cmock_guts_index);
  UNITY_TEST_ASSERT_NOT_NULL(cmock_call_instance, cmock_line, CMockStringOutOfMemory);
  memset(cmock_call_instance, 0, sizeof(*cmock_call_instance));
  Mock.board_io__get_sw1_CallInstance = CMock_Guts_MemChain(Mock.board_io__get_sw1_CallInstance, cmock_guts_index);
  Mock.board_io__get_sw1_IgnoreBool = (int)0;
  cmock_call_instance->LineNumber = cmock_line;
  cmock_call_instance->ExceptionToThrow = CEXCEPTION_NONE;
  cmock_call_instance->ExpectAnyArgsBool = (int)0;
  cmock_call_instance->ReturnVal = cmock_to_return;
  Mock.board_io__get_sw1_IgnoreBool = (int)1;
}

void board_io__get_sw1_CMockExpectAndReturn(UNITY_LINE_TYPE cmock_line, gpio_s cmock_to_return)
{
  CMOCK_MEM_INDEX_TYPE cmock_guts_index = CMock_Guts_MemNew(sizeof(CMOCK_board_io__get_sw1_CALL_INSTANCE));
  CMOCK_board_io__get_sw1_CALL_INSTANCE* cmock_call_instance = (CMOCK_board_io__get_sw1_CALL_INSTANCE*)CMock_Guts_GetAddressFor(cmock_guts_index);
  UNITY_TEST_ASSERT_NOT_NULL(cmock_call_instance, cmock_line, CMockStringOutOfMemory);
  memset(cmock_call_instance, 0, sizeof(*cmock_call_instance));
  Mock.board_io__get_sw1_CallInstance = CMock_Guts_MemChain(Mock.board_io__get_sw1_CallInstance, cmock_guts_index);
  Mock.board_io__get_sw1_IgnoreBool = (int)0;
  cmock_call_instance->LineNumber = cmock_line;
  cmock_call_instance->ExceptionToThrow = CEXCEPTION_NONE;
  cmock_call_instance->ExpectAnyArgsBool = (int)0;
  memcpy((void*)(&cmock_call_instance->ReturnVal), (void*)(&cmock_to_return),
         sizeof(gpio_s[sizeof(cmock_to_return) == sizeof(gpio_s) ? 1 : -1])); /* add gpio_s to :treat_as_array if this causes an error */
}

void board_io__get_sw1_AddCallback(CMOCK_board_io__get_sw1_CALLBACK Callback)
{
  Mock.board_io__get_sw1_IgnoreBool = (int)0;
  Mock.board_io__get_sw1_CallbackBool = (int)1;
  Mock.board_io__get_sw1_CallbackFunctionPointer = Callback;
}

void board_io__get_sw1_Stub(CMOCK_board_io__get_sw1_CALLBACK Callback)
{
  Mock.board_io__get_sw1_IgnoreBool = (int)0;
  Mock.board_io__get_sw1_CallbackBool = (int)0;
  Mock.board_io__get_sw1_CallbackFunctionPointer = Callback;
}

void board_io__get_sw1_CMockExpectAndThrow(UNITY_LINE_TYPE cmock_line, CEXCEPTION_T cmock_to_throw)
{
  CMOCK_MEM_INDEX_TYPE cmock_guts_index = CMock_Guts_MemNew(sizeof(CMOCK_board_io__get_sw1_CALL_INSTANCE));
  CMOCK_board_io__get_sw1_CALL_INSTANCE* cmock_call_instance = (CMOCK_board_io__get_sw1_CALL_INSTANCE*)CMock_Guts_GetAddressFor(cmock_guts_index);
  UNITY_TEST_ASSERT_NOT_NULL(cmock_call_instance, cmock_line, CMockStringOutOfMemory);
  memset(cmock_call_instance, 0, sizeof(*cmock_call_instance));
  Mock.board_io__get_sw1_CallInstance = CMock_Guts_MemChain(Mock.board_io__get_sw1_CallInstance, cmock_guts_index);
  Mock.board_io__get_sw1_IgnoreBool = (int)0;
  cmock_call_instance->LineNumber = cmock_line;
  cmock_call_instance->ExceptionToThrow = CEXCEPTION_NONE;
  cmock_call_instance->ExpectAnyArgsBool = (int)0;
  cmock_call_instance->ExceptionToThrow = cmock_to_throw;
}

gpio_s board_io__get_sw2(void)
{
  UNITY_LINE_TYPE cmock_line = TEST_LINE_NUM;
  CMOCK_board_io__get_sw2_CALL_INSTANCE* cmock_call_instance;
  UNITY_SET_DETAIL(CMockString_board_io__get_sw2);
  cmock_call_instance = (CMOCK_board_io__get_sw2_CALL_INSTANCE*)CMock_Guts_GetAddressFor(Mock.board_io__get_sw2_CallInstance);
  Mock.board_io__get_sw2_CallInstance = CMock_Guts_MemNext(Mock.board_io__get_sw2_CallInstance);
  if (Mock.board_io__get_sw2_IgnoreBool)
  {
    UNITY_CLR_DETAILS();
    if (cmock_call_instance == NULL)
      return Mock.board_io__get_sw2_FinalReturn;
    memcpy((void*)(&Mock.board_io__get_sw2_FinalReturn), (void*)(&cmock_call_instance->ReturnVal),
         sizeof(gpio_s[sizeof(cmock_call_instance->ReturnVal) == sizeof(gpio_s) ? 1 : -1])); /* add gpio_s to :treat_as_array if this causes an error */
    return cmock_call_instance->ReturnVal;
  }
  if (!Mock.board_io__get_sw2_CallbackBool &&
      Mock.board_io__get_sw2_CallbackFunctionPointer != NULL)
  {
    gpio_s ret = Mock.board_io__get_sw2_CallbackFunctionPointer(Mock.board_io__get_sw2_CallbackCalls++);
    UNITY_CLR_DETAILS();
    return ret;
  }
  UNITY_TEST_ASSERT_NOT_NULL(cmock_call_instance, cmock_line, CMockStringCalledMore);
  cmock_line = cmock_call_instance->LineNumber;
  if (Mock.board_io__get_sw2_CallbackFunctionPointer != NULL)
  {
    cmock_call_instance->ReturnVal = Mock.board_io__get_sw2_CallbackFunctionPointer(Mock.board_io__get_sw2_CallbackCalls++);
  }
  if (cmock_call_instance->ExceptionToThrow != CEXCEPTION_NONE)
  {
    UNITY_CLR_DETAILS();
    Throw(cmock_call_instance->ExceptionToThrow);
  }
  UNITY_CLR_DETAILS();
  return cmock_call_instance->ReturnVal;
}

void board_io__get_sw2_CMockIgnoreAndReturn(UNITY_LINE_TYPE cmock_line, gpio_s cmock_to_return)
{
  CMOCK_MEM_INDEX_TYPE cmock_guts_index = CMock_Guts_MemNew(sizeof(CMOCK_board_io__get_sw2_CALL_INSTANCE));
  CMOCK_board_io__get_sw2_CALL_INSTANCE* cmock_call_instance = (CMOCK_board_io__get_sw2_CALL_INSTANCE*)CMock_Guts_GetAddressFor(cmock_guts_index);
  UNITY_TEST_ASSERT_NOT_NULL(cmock_call_instance, cmock_line, CMockStringOutOfMemory);
  memset(cmock_call_instance, 0, sizeof(*cmock_call_instance));
  Mock.board_io__get_sw2_CallInstance = CMock_Guts_MemChain(Mock.board_io__get_sw2_CallInstance, cmock_guts_index);
  Mock.board_io__get_sw2_IgnoreBool = (int)0;
  cmock_call_instance->LineNumber = cmock_line;
  cmock_call_instance->ExceptionToThrow = CEXCEPTION_NONE;
  cmock_call_instance->ExpectAnyArgsBool = (int)0;
  cmock_call_instance->ReturnVal = cmock_to_return;
  Mock.board_io__get_sw2_IgnoreBool = (int)1;
}

void board_io__get_sw2_CMockExpectAndReturn(UNITY_LINE_TYPE cmock_line, gpio_s cmock_to_return)
{
  CMOCK_MEM_INDEX_TYPE cmock_guts_index = CMock_Guts_MemNew(sizeof(CMOCK_board_io__get_sw2_CALL_INSTANCE));
  CMOCK_board_io__get_sw2_CALL_INSTANCE* cmock_call_instance = (CMOCK_board_io__get_sw2_CALL_INSTANCE*)CMock_Guts_GetAddressFor(cmock_guts_index);
  UNITY_TEST_ASSERT_NOT_NULL(cmock_call_instance, cmock_line, CMockStringOutOfMemory);
  memset(cmock_call_instance, 0, sizeof(*cmock_call_instance));
  Mock.board_io__get_sw2_CallInstance = CMock_Guts_MemChain(Mock.board_io__get_sw2_CallInstance, cmock_guts_index);
  Mock.board_io__get_sw2_IgnoreBool = (int)0;
  cmock_call_instance->LineNumber = cmock_line;
  cmock_call_instance->ExceptionToThrow = CEXCEPTION_NONE;
  cmock_call_instance->ExpectAnyArgsBool = (int)0;
  memcpy((void*)(&cmock_call_instance->ReturnVal), (void*)(&cmock_to_return),
         sizeof(gpio_s[sizeof(cmock_to_return) == sizeof(gpio_s) ? 1 : -1])); /* add gpio_s to :treat_as_array if this causes an error */
}

void board_io__get_sw2_AddCallback(CMOCK_board_io__get_sw2_CALLBACK Callback)
{
  Mock.board_io__get_sw2_IgnoreBool = (int)0;
  Mock.board_io__get_sw2_CallbackBool = (int)1;
  Mock.board_io__get_sw2_CallbackFunctionPointer = Callback;
}

void board_io__get_sw2_Stub(CMOCK_board_io__get_sw2_CALLBACK Callback)
{
  Mock.board_io__get_sw2_IgnoreBool = (int)0;
  Mock.board_io__get_sw2_CallbackBool = (int)0;
  Mock.board_io__get_sw2_CallbackFunctionPointer = Callback;
}

void board_io__get_sw2_CMockExpectAndThrow(UNITY_LINE_TYPE cmock_line, CEXCEPTION_T cmock_to_throw)
{
  CMOCK_MEM_INDEX_TYPE cmock_guts_index = CMock_Guts_MemNew(sizeof(CMOCK_board_io__get_sw2_CALL_INSTANCE));
  CMOCK_board_io__get_sw2_CALL_INSTANCE* cmock_call_instance = (CMOCK_board_io__get_sw2_CALL_INSTANCE*)CMock_Guts_GetAddressFor(cmock_guts_index);
  UNITY_TEST_ASSERT_NOT_NULL(cmock_call_instance, cmock_line, CMockStringOutOfMemory);
  memset(cmock_call_instance, 0, sizeof(*cmock_call_instance));
  Mock.board_io__get_sw2_CallInstance = CMock_Guts_MemChain(Mock.board_io__get_sw2_CallInstance, cmock_guts_index);
  Mock.board_io__get_sw2_IgnoreBool = (int)0;
  cmock_call_instance->LineNumber = cmock_line;
  cmock_call_instance->ExceptionToThrow = CEXCEPTION_NONE;
  cmock_call_instance->ExpectAnyArgsBool = (int)0;
  cmock_call_instance->ExceptionToThrow = cmock_to_throw;
}

gpio_s board_io__get_sw3(void)
{
  UNITY_LINE_TYPE cmock_line = TEST_LINE_NUM;
  CMOCK_board_io__get_sw3_CALL_INSTANCE* cmock_call_instance;
  UNITY_SET_DETAIL(CMockString_board_io__get_sw3);
  cmock_call_instance = (CMOCK_board_io__get_sw3_CALL_INSTANCE*)CMock_Guts_GetAddressFor(Mock.board_io__get_sw3_CallInstance);
  Mock.board_io__get_sw3_CallInstance = CMock_Guts_MemNext(Mock.board_io__get_sw3_CallInstance);
  if (Mock.board_io__get_sw3_IgnoreBool)
  {
    UNITY_CLR_DETAILS();
    if (cmock_call_instance == NULL)
      return Mock.board_io__get_sw3_FinalReturn;
    memcpy((void*)(&Mock.board_io__get_sw3_FinalReturn), (void*)(&cmock_call_instance->ReturnVal),
         sizeof(gpio_s[sizeof(cmock_call_instance->ReturnVal) == sizeof(gpio_s) ? 1 : -1])); /* add gpio_s to :treat_as_array if this causes an error */
    return cmock_call_instance->ReturnVal;
  }
  if (!Mock.board_io__get_sw3_CallbackBool &&
      Mock.board_io__get_sw3_CallbackFunctionPointer != NULL)
  {
    gpio_s ret = Mock.board_io__get_sw3_CallbackFunctionPointer(Mock.board_io__get_sw3_CallbackCalls++);
    UNITY_CLR_DETAILS();
    return ret;
  }
  UNITY_TEST_ASSERT_NOT_NULL(cmock_call_instance, cmock_line, CMockStringCalledMore);
  cmock_line = cmock_call_instance->LineNumber;
  if (Mock.board_io__get_sw3_CallbackFunctionPointer != NULL)
  {
    cmock_call_instance->ReturnVal = Mock.board_io__get_sw3_CallbackFunctionPointer(Mock.board_io__get_sw3_CallbackCalls++);
  }
  if (cmock_call_instance->ExceptionToThrow != CEXCEPTION_NONE)
  {
    UNITY_CLR_DETAILS();
    Throw(cmock_call_instance->ExceptionToThrow);
  }
  UNITY_CLR_DETAILS();
  return cmock_call_instance->ReturnVal;
}

void board_io__get_sw3_CMockIgnoreAndReturn(UNITY_LINE_TYPE cmock_line, gpio_s cmock_to_return)
{
  CMOCK_MEM_INDEX_TYPE cmock_guts_index = CMock_Guts_MemNew(sizeof(CMOCK_board_io__get_sw3_CALL_INSTANCE));
  CMOCK_board_io__get_sw3_CALL_INSTANCE* cmock_call_instance = (CMOCK_board_io__get_sw3_CALL_INSTANCE*)CMock_Guts_GetAddressFor(cmock_guts_index);
  UNITY_TEST_ASSERT_NOT_NULL(cmock_call_instance, cmock_line, CMockStringOutOfMemory);
  memset(cmock_call_instance, 0, sizeof(*cmock_call_instance));
  Mock.board_io__get_sw3_CallInstance = CMock_Guts_MemChain(Mock.board_io__get_sw3_CallInstance, cmock_guts_index);
  Mock.board_io__get_sw3_IgnoreBool = (int)0;
  cmock_call_instance->LineNumber = cmock_line;
  cmock_call_instance->ExceptionToThrow = CEXCEPTION_NONE;
  cmock_call_instance->ExpectAnyArgsBool = (int)0;
  cmock_call_instance->ReturnVal = cmock_to_return;
  Mock.board_io__get_sw3_IgnoreBool = (int)1;
}

void board_io__get_sw3_CMockExpectAndReturn(UNITY_LINE_TYPE cmock_line, gpio_s cmock_to_return)
{
  CMOCK_MEM_INDEX_TYPE cmock_guts_index = CMock_Guts_MemNew(sizeof(CMOCK_board_io__get_sw3_CALL_INSTANCE));
  CMOCK_board_io__get_sw3_CALL_INSTANCE* cmock_call_instance = (CMOCK_board_io__get_sw3_CALL_INSTANCE*)CMock_Guts_GetAddressFor(cmock_guts_index);
  UNITY_TEST_ASSERT_NOT_NULL(cmock_call_instance, cmock_line, CMockStringOutOfMemory);
  memset(cmock_call_instance, 0, sizeof(*cmock_call_instance));
  Mock.board_io__get_sw3_CallInstance = CMock_Guts_MemChain(Mock.board_io__get_sw3_CallInstance, cmock_guts_index);
  Mock.board_io__get_sw3_IgnoreBool = (int)0;
  cmock_call_instance->LineNumber = cmock_line;
  cmock_call_instance->ExceptionToThrow = CEXCEPTION_NONE;
  cmock_call_instance->ExpectAnyArgsBool = (int)0;
  memcpy((void*)(&cmock_call_instance->ReturnVal), (void*)(&cmock_to_return),
         sizeof(gpio_s[sizeof(cmock_to_return) == sizeof(gpio_s) ? 1 : -1])); /* add gpio_s to :treat_as_array if this causes an error */
}

void board_io__get_sw3_AddCallback(CMOCK_board_io__get_sw3_CALLBACK Callback)
{
  Mock.board_io__get_sw3_IgnoreBool = (int)0;
  Mock.board_io__get_sw3_CallbackBool = (int)1;
  Mock.board_io__get_sw3_CallbackFunctionPointer = Callback;
}

void board_io__get_sw3_Stub(CMOCK_board_io__get_sw3_CALLBACK Callback)
{
  Mock.board_io__get_sw3_IgnoreBool = (int)0;
  Mock.board_io__get_sw3_CallbackBool = (int)0;
  Mock.board_io__get_sw3_CallbackFunctionPointer = Callback;
}

void board_io__get_sw3_CMockExpectAndThrow(UNITY_LINE_TYPE cmock_line, CEXCEPTION_T cmock_to_throw)
{
  CMOCK_MEM_INDEX_TYPE cmock_guts_index = CMock_Guts_MemNew(sizeof(CMOCK_board_io__get_sw3_CALL_INSTANCE));
  CMOCK_board_io__get_sw3_CALL_INSTANCE* cmock_call_instance = (CMOCK_board_io__get_sw3_CALL_INSTANCE*)CMock_Guts_GetAddressFor(cmock_guts_index);
  UNITY_TEST_ASSERT_NOT_NULL(cmock_call_instance, cmock_line, CMockStringOutOfMemory);
  memset(cmock_call_instance, 0, sizeof(*cmock_call_instance));
  Mock.board_io__get_sw3_CallInstance = CMock_Guts_MemChain(Mock.board_io__get_sw3_CallInstance, cmock_guts_index);
  Mock.board_io__get_sw3_IgnoreBool = (int)0;
  cmock_call_instance->LineNumber = cmock_line;
  cmock_call_instance->ExceptionToThrow = CEXCEPTION_NONE;
  cmock_call_instance->ExpectAnyArgsBool = (int)0;
  cmock_call_instance->ExceptionToThrow = cmock_to_throw;
}

